"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { defaultOnboardingDraft, ensureUserRecord } from "@/lib/supabase/ensure-user-record";
import { cardClass, inputClass, pageBg } from "@/lib/challenge-ui";
import { computeBodyPlan, computeQuranPlan, daysBetween, generateWeeklyWorkoutPlan, limitFields, safeFirstName, weightPace } from "@/lib/onboarding-coach";

type Draft = Record<string, any>;
const feet = ["4", "5", "6", "7"];
const inches = Array.from({ length: 12 }, (_, index) => String(index));
const exerciseTypes = ["walking", "boxing", "gym", "bodyweight", "swimming", "running", "cycling", "sports", "yoga"];
const equipment = ["none", "dumbbells", "full home gym", "gym membership", "boxing gear", "pool"];
const injuries = ["none", "knee", "back", "shoulder", "asthma", "low stamina"];
const worship = ["5 daily salah on time", "daily dhikr", "daily dua", "masjid 3x/week", "Islamic learning daily"];
const goals = ["Boxing", "Hygiene", "School", "Business", "Reading", "Confidence", "Sleep schedule", "Money", "Cleaning", "Family", "Character"];
const taskSuggestions = ["Practice boxing footwork for 20 min", "Clean the kitchen and do dishes", "Read 10 pages and write one note", "Work on business outreach for 30 min"];
const stepTitles = ["Niyyah", "Basic Info", "Challenge Length", "Sleep & Fajr", "Body Plan", "Weekly Workout", "Qur'an Plan", "Personal Goals", "Limits & Privacy"];

function Field({ label, children, hint }: { label: string; children: React.ReactNode; hint?: string }) { return <label className="block"><span className="text-sm font-bold text-slate-700">{label}</span><div className="mt-1">{children}</div>{hint && <p className="mt-1 text-xs text-slate-500">{hint}</p>}</label>; }
function Select({ value, onChange, options, label }: { value: string; onChange: (v: string) => void; options: string[]; label: string }) { return <Field label={label}><select className={inputClass} value={value || ""} onChange={(e) => onChange(e.target.value)}><option value="">Choose...</option>{options.map((o) => <option key={o} value={o}>{o}</option>)}</select></Field>; }
function ChipGroup({ options, values, onChange }: { options: string[]; values: string[]; onChange: (v: string[]) => void }) { const safeValues = Array.isArray(values) ? values : values ? [String(values)] : []; return <div className="flex flex-wrap gap-2">{options.map((option) => <button type="button" key={option} onClick={() => safeValues.includes(option) ? onChange(safeValues.filter((x) => x !== option)) : onChange([...safeValues, option])} className={`rounded-full px-4 py-2 text-sm font-bold ${safeValues.includes(option) ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-700"}`}>{option}</button>)}</div>; }
function singleChoiceClass(active: boolean) { return `rounded-full px-4 py-2 text-sm font-black ${active ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-700"}`; }

export default function OnboardingCoachFlow() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [userId, setUserId] = useState("");
  const [message, setMessage] = useState("");
  const [draft, setDraft] = useState<Draft>({});

  useEffect(() => {
    async function load() {
      const supabase = createSupabaseBrowserClient();
      const { data } = await supabase.auth.getUser();
      if (!data.user) { router.push("/login"); return; }
      const record = await ensureUserRecord(data.user);
      setUserId(record.id);
      const saved = (record.onboarding_draft || {}) as Draft;
      const today = new Date().toISOString().slice(0, 10);
      const end = new Date(Date.now() + 89 * 86400000).toISOString().slice(0, 10);
      setDraft({ ...(defaultOnboardingDraft(record.name) as Draft), name: record.name, heightFeet: "5", heightInches: "8", workoutMinutes: "45", workoutDays: "4", measurementUnit: "pages", murajaaCycleDays: "10", activityLevel: "Moderate", startDate: today, endDate: end, ...saved });
    }
    load();
  }, [router]);

  function set(key: string, value: any) { setDraft((d) => ({ ...d, [key]: value })); }
  const challengeDays = useMemo(() => daysBetween(draft.startDate, draft.endDate), [draft.startDate, draft.endDate]);
  const bodyPlan = useMemo(() => computeBodyPlan({ ...draft, challengeDays }), [draft, challengeDays]);
  const quranPlan = useMemo(() => computeQuranPlan({ unit: draft.measurementUnit, currentHifdh: draft.currentHifdhAmount, goalHifdh: draft.goalHifdhAmount, challengeDays, murajaaCycleDays: draft.murajaaCycleDays }), [draft.measurementUnit, draft.currentHifdhAmount, draft.goalHifdhAmount, draft.murajaaCycleDays, challengeDays]);
  const workoutPlan = useMemo(() => generateWeeklyWorkoutPlan(draft.exerciseTypes || [], Number(draft.workoutDays || bodyPlan.exerciseDaysPerWeek), draft.injuries || []), [draft.exerciseTypes, draft.workoutDays, draft.injuries, bodyPlan.exerciseDaysPerWeek]);
  const pace = weightPace(draft.currentWeightLbs, draft.goalWeightLbs, challengeDays || 90);
  const first = safeFirstName(draft.name) || "friend";

  async function save(nextStep?: number) { if (!userId) return; const supabase = createSupabaseBrowserClient(); await supabase.from("users").update({ onboarding_draft: draft }).eq("id", userId); if (nextStep) setStep(nextStep); }
  function validate() {
    if (step === 2 && (!draft.age || Number(draft.age) < 13 || Number(draft.age) > 100 || !draft.gender || !draft.currentWeightLbs || !draft.goalWeightLbs)) return "Complete basic info first.";
    if (step === 3 && (!draft.startDate || !draft.endDate || challengeDays < 30 || challengeDays > 365)) return "Challenge must be 30 to 365 days.";
    if (step === 4 && (!draft.city || !draft.currentSleepHours)) return "Add your city and current sleep average.";
    if (step === 5 && (!draft.activityLevel)) return "Pick an activity level.";
    if (step === 6 && (!draft.exerciseTypes?.length || !draft.equipment?.length || !draft.injuries?.length)) return "Choose workout preferences, equipment, and limitations.";
    if (step === 7 && ((!draft.currentHifdhAmount && draft.currentHifdhAmount !== 0) || (!draft.goalHifdhAmount && draft.goalHifdhAmount !== 0) || !draft.worshipGoals?.length)) return "Complete Qur'an and worship goals.";
    if (step === 8 && (!draft.goal1 || !draft.goal1Task || !draft.goal2 || !draft.goal2Task)) return "Add both personal goals and daily tasks.";
    return "";
  }
  async function next() { const error = validate(); if (error) { setMessage(error); return; } setMessage(""); if (step < 9) await save(step + 1); else await buildPlan(); }
  async function buildPlan() {
    const planDraft = { ...draft, calorieTarget: String(bodyPlan.dailyTarget), stepTarget: String(bodyPlan.dailySteps), waterTarget: String(bodyPlan.dailyWaterCups), workoutMinutes: String(bodyPlan.exerciseMinPerSession), workoutDays: String(bodyPlan.exerciseDaysPerWeek), dailyMemorizeGoal: String(Math.round(quranPlan.newPerDay * 10) / 10), dailyReviewGoal: String(quranPlan.murajaaPerDay), coachPlan: { bodyPlan, quranPlan, workoutPlan } };
    const supabase = createSupabaseBrowserClient();
    await supabase.from("users").update({ onboarding_draft: planDraft, onboarding_complete: false }).eq("id", userId);
    router.push("/onboarding/plan");
  }

  return <main className={pageBg}><div className="mx-auto max-w-4xl space-y-5"><section className="rounded-[2rem] bg-slate-950 p-6 text-white"><p className="text-sm font-bold text-emerald-300">Step {step} of 9</p><h1 className="mt-1 text-3xl font-black">{stepTitles[step - 1]}</h1><div className="mt-4 grid grid-cols-9 gap-1">{Array.from({ length: 9 }, (_, i) => <div key={i} className={`h-2 rounded-full ${i < step ? "bg-emerald-400" : "bg-white/10"}`} />)}</div></section><section className={cardClass}>{step === 1 && <Welcome first={first} />}{step === 2 && <BasicInfo draft={draft} set={set} pace={pace} />}{step === 3 && <ChallengeLength draft={draft} setDraft={setDraft} challengeDays={challengeDays} pace={pace} />}{step === 4 && <SleepFajr draft={draft} set={set} />}{step === 5 && <BodyPlan draft={draft} set={set} plan={bodyPlan} />}{step === 6 && <ExercisePlan draft={draft} set={set} plan={workoutPlan} />}{step === 7 && <QuranPlan draft={draft} set={set} plan={quranPlan} />}{step === 8 && <PersonalGoals draft={draft} set={set} challengeDays={challengeDays} />}{step === 9 && <LimitsPrivacy draft={draft} set={set} />}{message && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{message}</p>}<div className="mt-6 flex justify-between gap-3"><button onClick={() => setStep(Math.max(1, step - 1))} className="rounded-full bg-slate-100 px-5 py-3 font-bold">Back</button><button onClick={next} className="rounded-full bg-emerald-600 px-5 py-3 font-black text-white">{step < 9 ? "Next" : "Preview my plan"}</button></div></section></div></main>;
}

function Welcome({ first }: { first: string }) { return <div className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-emerald-900"><svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 12.8A8.5 8.5 0 1 1 11.2 3 6.5 6.5 0 0 0 21 12.8Z" /></svg></div><p className="mt-6 text-lg font-black text-emerald-700">Bismillāh ar-Raḥmān ar-Raḥīm</p><p dir="rtl" className="mt-2 text-3xl font-black leading-loose">بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</p><h2 className="mt-6 text-3xl font-black">As-salāmu ʿalaykum, {first}.</h2><p className="mx-auto mt-4 max-w-2xl text-slate-600">This challenge is between you and Allah ﷻ. Every answer shapes a real plan. Be honest — the plan only works if the inputs are real.</p><p className="mt-6 text-sm font-bold text-slate-500">Step 1 of 9 • takes about 8 minutes</p></div>; }
function BasicInfo({ draft, set, pace }: any) { return <div className="grid gap-4 md:grid-cols-2"><Field label="Age"><input className={inputClass} type="number" min={13} max={100} value={draft.age || ""} onChange={(e) => set("age", e.target.value)} /></Field><Select label="Gender" value={draft.gender || ""} onChange={(v) => set("gender", v)} options={["Male", "Female", "Prefer not to say"]} /><Select label="Height feet" value={draft.heightFeet || "5"} onChange={(v) => set("heightFeet", v)} options={feet} /><Select label="Height inches" value={draft.heightInches || "8"} onChange={(v) => set("heightInches", v)} options={inches} /><Field label="Current weight (lbs)"><input className={inputClass} type="number" value={draft.currentWeightLbs || ""} onChange={(e) => set("currentWeightLbs", e.target.value)} /></Field><Field label="Goal weight (lbs)"><input className={inputClass} type="number" value={draft.goalWeightLbs || ""} onChange={(e) => set("goalWeightLbs", e.target.value)} /></Field>{pace && <p className={`md:col-span-2 rounded-2xl p-4 font-bold ${pace.isFast ? "bg-amber-50 text-amber-900" : "bg-emerald-50 text-emerald-900"}`}>You want to {pace.kind} about {Math.abs(pace.weekly)} lbs/week. {pace.isFast ? `That is faster than the recommended ${pace.safeMax} lbs/week. We will keep the plan realistic.` : "That pace looks reasonable."}</p>}</div>; }
function ChallengeLength({ draft, setDraft, challengeDays, pace }: any) { return <div className="grid gap-4 md:grid-cols-2"><Field label="Start date"><input className={inputClass} type="date" value={draft.startDate || ""} onChange={(e) => setDraft((d: any) => ({ ...d, startDate: e.target.value }))} /></Field><Field label="End date"><input className={inputClass} type="date" value={draft.endDate || ""} onChange={(e) => setDraft((d: any) => ({ ...d, endDate: e.target.value }))} /></Field><div className="md:col-span-2 flex flex-wrap gap-2">{[30, 60, 90, 180].map((days) => <button key={days} onClick={() => { const start = draft.startDate || new Date().toISOString().slice(0, 10); const end = new Date(new Date(`${start}T00:00:00`).getTime() + (days - 1) * 86400000).toISOString().slice(0, 10); setDraft((d: any) => ({ ...d, startDate: start, endDate: end })); }} className="rounded-full bg-emerald-100 px-4 py-2 text-sm font-bold text-emerald-800">{days} days</button>)}</div><p className="md:col-span-2 rounded-2xl bg-slate-50 p-4 font-bold">Your challenge is {challengeDays || 0} days. You need about {challengeDays ? (100 / challengeDays).toFixed(1) : "—"} points/day.</p>{pace?.isFast && <p className="md:col-span-2 rounded-2xl bg-amber-50 p-4 font-bold text-amber-900">Your weight goal may be too fast at this length. Consider 90 or 180 days for a safer pace.</p>}</div>; }
function SleepFajr({ draft, set }: any) { const fajr = draft.fajrTime || "04:45"; return <div className="grid gap-4 md:grid-cols-2"><Field label="City, Country" hint="Used to anchor your sleep plan to Fajr."><input className={inputClass} placeholder="Chicago, US" value={draft.city || ""} onChange={(e) => set("city", e.target.value)} /></Field><Field label="Tomorrow's Fajr time"><input className={inputClass} type="time" value={fajr} onChange={(e) => set("fajrTime", e.target.value)} /></Field><Field label="Target wake-up"><input className={inputClass} type="time" value={draft.wakeTime || "04:30"} onChange={(e) => set("wakeTime", e.target.value)} /></Field><Field label="Target bedtime"><input className={inputClass} type="time" value={draft.bedtime || "21:00"} onChange={(e) => set("bedtime", e.target.value)} /></Field><Field label="Current average sleep (hours)"><input className={inputClass} type="number" value={draft.currentSleepHours || ""} onChange={(e) => set("currentSleepHours", e.target.value)} /></Field><p className="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-900 md:col-span-2">Sleep is your foundation. This plan aims for early sleep, wake before Fajr, and enough time for wudu and prayer.</p></div>; }
function BodyPlan({ draft, set, plan }: any) { return <div className="space-y-5"><Field label="Activity level"><div className="flex flex-wrap gap-2">{["Sedentary", "Light", "Moderate", "Active"].map((level) => <button key={level} onClick={() => set("activityLevel", level)} className={singleChoiceClass((draft.activityLevel || "Moderate") === level)}>{level}</button>)}</div></Field><div className="rounded-[1.5rem] bg-slate-950 p-5 text-white"><p className="text-sm font-black text-emerald-300">Your body plan</p><div className="mt-4 grid gap-3 md:grid-cols-2"><PlanLine label="Maintenance" value={`${plan.tdee} kcal`} /><PlanLine label="Daily target" value={`${plan.dailyTarget} kcal`} /><PlanLine label="Steps" value={`${plan.dailySteps.toLocaleString()}/day`} /><PlanLine label="Water" value={`${plan.dailyWaterCups} cups/day`} /><PlanLine label="Exercise" value={`${plan.exerciseMinPerSession} min • ${plan.exerciseDaysPerWeek} days/week`} /><PlanLine label="Weight pace" value={`${Math.abs(plan.weeklyChange)} lbs/week`} /></div></div></div>; }
function ExercisePlan({ draft, set, plan }: any) { return <div className="space-y-5"><Field label="Preferred types"><ChipGroup options={exerciseTypes} values={draft.exerciseTypes || []} onChange={(v) => set("exerciseTypes", v)} /></Field><Field label="Equipment access"><ChipGroup options={equipment} values={draft.equipment || []} onChange={(v) => set("equipment", v)} /></Field><Field label="Injuries / limitations"><ChipGroup options={injuries} values={draft.injuries || []} onChange={(v) => set("injuries", v)} /></Field><Field label="Workout days per week"><input className={inputClass} type="number" min={1} max={7} value={draft.workoutDays || "4"} onChange={(e) => set("workoutDays", e.target.value)} /></Field><div className="rounded-[1.5rem] bg-slate-50 p-5"><p className="font-black">Your weekly workout</p><div className="mt-3 space-y-2">{plan.map((item: any) => <div key={item.day} className="flex justify-between rounded-xl bg-white p-3 text-sm"><span className="font-black">{item.day}</span><span>{item.minutes ? `${item.minutes} min • ` : ""}{item.name}</span></div>)}</div></div></div>; }
function QuranPlan({ draft, set, plan }: any) { return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><Select label="Measurement unit" value={draft.measurementUnit || "pages"} onChange={(v) => set("measurementUnit", v)} options={["lines", "pages", "surahs", "juz"]} /><Field label="Current hifdh"><input className={inputClass} type="number" min={0} value={draft.currentHifdhAmount || ""} onChange={(e) => set("currentHifdhAmount", e.target.value)} /></Field><Field label="Goal hifdh"><input className={inputClass} type="number" min={0} value={draft.goalHifdhAmount || ""} onChange={(e) => set("goalHifdhAmount", e.target.value)} /></Field><Select label="Murajaa cycle" value={draft.murajaaCycleDays || "10"} onChange={(v) => set("murajaaCycleDays", v)} options={["5", "7", "10", "14", "30"]} /></div><div className="rounded-[1.5rem] bg-slate-950 p-5 text-white"><p className="text-sm font-black text-emerald-300">Your Qur'an plan</p><div className="mt-4 grid gap-3 md:grid-cols-2"><PlanLine label="New memorization" value={plan.memorizationSchedule} /><PlanLine label="Murajaa" value={`${plan.murajaaPerDay} ${plan.unit}/day`} /><PlanLine label="Cycle" value={`Full review every ${plan.murajaaCycleDays} days`} /><PlanLine label="Daily time" value={`~${plan.dailyMinutes} minutes`} /></div></div><Field label="Worship goals"><ChipGroup options={worship} values={draft.worshipGoals || []} onChange={(v) => set("worshipGoals", v)} /></Field><Field label="How often do you practice tajweed?"><div className="flex flex-wrap gap-2">{["Daily", "A few times a week", "Once a week", "Not yet"].map((option) => <button key={option} onClick={() => set("tajweedPractice", option)} className={singleChoiceClass(draft.tajweedPractice === option)}>{option}</button>)}</div></Field></div>; }
function PersonalGoals({ draft, set, challengeDays }: any) { const totalWeeks = Math.round((challengeDays || 90) / 7); return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><PersonalGoalCard slot="1" draft={draft} set={set} /><PersonalGoalCard slot="2" draft={draft} set={set} /></div><div className="rounded-[1.5rem] bg-emerald-50 p-5 text-emerald-950"><p className="font-black">Your 2 goals over {challengeDays || 90} days</p><p className="mt-2 text-sm font-semibold">1. {draft.goal1 || "Goal 1"}: {draft.goal1Task || "daily task"} → about {Number(draft.goal1Days || 5) * totalWeeks} sessions</p><p className="mt-1 text-sm font-semibold">2. {draft.goal2 || "Goal 2"}: {draft.goal2Task || "daily task"} → about {Number(draft.goal2Days || 5) * totalWeeks} sessions</p></div></div>; }
function PersonalGoalCard({ slot, draft, set }: any) { return <div className="rounded-2xl bg-slate-50 p-4"><Select label={`Goal ${slot}`} value={draft[`goal${slot}`] || ""} onChange={(v) => set(`goal${slot}`, v)} options={goals} /><Field label="Daily task"><input className={inputClass} placeholder="Practice for 20 minutes" value={draft[`goal${slot}Task`] || ""} onChange={(e) => set(`goal${slot}Task`, e.target.value)} /></Field><div className="mt-2 flex flex-wrap gap-2">{taskSuggestions.map((task) => <button key={task} type="button" onClick={() => set(`goal${slot}Task`, task)} className="rounded-full bg-white px-3 py-2 text-xs font-bold text-slate-700">{task}</button>)}</div><Field label="Days per week"><input className={inputClass} type="number" min={1} max={7} value={draft[`goal${slot}Days`] || "5"} onChange={(e) => set(`goal${slot}Days`, e.target.value)} /></Field><Select label="Proof method" value={draft[`goal${slot}Proof`] || "log entry"} onChange={(v) => set(`goal${slot}Proof`, v)} options={["photo", "log entry", "time tracked", "count", "free text"]} /></div>; }
function LimitsPrivacy({ draft, set }: any) { const groups = ["Money", "Food limits", "Screens"]; return <div className="space-y-5"><p className="rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-700">Skip any limit you do not want to track. You can edit these anytime.</p>{groups.map((group) => <details key={group} open className="rounded-2xl bg-slate-50 p-4"><summary className="cursor-pointer text-xl font-black">{group}</summary><div className="mt-4 grid gap-4 md:grid-cols-2">{limitFields.filter((field) => field.group === group).map((field) => <Field key={field.key} label={field.label} hint={field.hint}><input className={inputClass} type="number" placeholder={field.defaultValue} value={draft[field.key] || ""} onChange={(e) => set(field.key, e.target.value)} /></Field>)}</div></details>)}<div className="rounded-2xl bg-emerald-50 p-4"><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={draft.showLeaderboard !== false} onChange={(e) => set("showLeaderboard", e.target.checked)} /> Show me on leaderboard</label><label className="mt-3 flex gap-2 text-sm font-bold"><input type="checkbox" checked={Boolean(draft.noPhoneAfterBed)} onChange={(e) => set("noPhoneAfterBed", e.target.checked)} /> No phone after bedtime</label></div></div>; }
function PlanLine({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/10 p-3"><p className="text-xs font-bold text-emerald-200">{label}</p><p className="mt-1 font-black text-white">{value}</p></div>; }
