"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { defaultOnboardingDraft, ensureUserRecord } from "@/lib/supabase/ensure-user-record";
import { cardClass, inputClass, pageBg } from "@/lib/challenge-ui";
import { computeBodyPlan, computeQuranPlan, daysBetween, safeFirstName, weightPace } from "@/lib/onboarding-coach";

type Draft = Record<string, any>;
const steps = ["Welcome", "Body", "Dates", "Activity", "Qur'an", "Goals", "Limits", "Pick Plan"];
const todayKey = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };
const plusDays = (start: string, days: number) => new Date(new Date(`${start}T00:00:00`).getTime() + (days - 1) * 86400000).toISOString().slice(0, 10);
const num = (v: any) => { const n = Number(v); return Number.isFinite(n) ? n : 0; };
function TextInput({ label, hint, type = "text", min, max, value, onChange }: any) { return <label className="block"><span className="text-sm font-bold text-slate-700">{label}</span><input className={inputClass} type={type} min={min} max={max} value={value ?? ""} onChange={(e) => onChange(e.target.value)} />{hint && <p className="mt-1 text-xs font-bold text-slate-500">{hint}</p>}</label>; }
function Pill({ active, children, onClick }: any) { return <button type="button" onClick={onClick} className={`rounded-full px-4 py-2 text-sm font-black ${active ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-700"}`}>{children}</button>; }
function choiceName(id: string) { return ({ high_protein_med: "High-Protein Mediterranean", calorie_counting: "Calorie-Counting Flexible", dash_whole_food: "DASH Whole Foods", beginner_3day_full: "3-Day Full Body", upper_lower_4day: "4-Day Upper/Lower", walk_bodyweight: "Walking + Bodyweight", steady_builder: "Steady Builder", reviewer: "Reviewer", maintainer: "Maintainer" } as Record<string, string>)[id] || id; }

export default function OnboardingFixedFlow() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [userId, setUserId] = useState("");
  const [draft, setDraft] = useState<Draft>({});
  const [error, setError] = useState("");
  const set = (k: string, v: any) => setDraft((d) => ({ ...d, [k]: v }));
  useEffect(() => { async function load() { const supabase = createSupabaseBrowserClient(); const { data } = await supabase.auth.getUser(); if (!data.user) { router.push("/login"); return; } const record = await ensureUserRecord(data.user); const saved = (record.onboarding_draft || {}) as Draft; const today = todayKey(); setUserId(record.id); setDraft({ ...(defaultOnboardingDraft(record.name) as Draft), name: record.name, startDate: today, endDate: plusDays(today, 90), measurementUnit: "pages", currentWeightLbs: "", goalWeightLbs: "", age: "", ...saved }); } load(); }, [router]);
  const days = useMemo(() => daysBetween(draft.startDate, draft.endDate), [draft.startDate, draft.endDate]);
  const bodyPlan = useMemo(() => computeBodyPlan({ ...draft, challengeDays: days || 90 }), [draft, days]);
  const quranPlan = useMemo(() => computeQuranPlan({ unit: draft.measurementUnit, currentHifdh: draft.currentHifdhAmount, goalHifdh: Math.max(num(draft.currentHifdhAmount), num(draft.goalHifdhAmount)), challengeDays: days || 90, murajaaCycleDays: draft.murajaaCycleDays || 10 }), [draft, days]);
  const pace = weightPace(draft.currentWeightLbs, draft.goalWeightLbs, days || 90);
  async function persist(next?: number) { if (!userId) return; const supabase = createSupabaseBrowserClient(); await supabase.from("users").update({ onboarding_draft: draft }).eq("id", userId); if (next) setStep(next); }
  function validate() {
    if (step === 2) { if (num(draft.age) < 13 || num(draft.age) > 100) return "Age must be 13–100."; if (num(draft.currentWeightLbs) < 50 || num(draft.goalWeightLbs) < 50) return "Weights must be realistic positive numbers."; }
    if (step === 3) { if (draft.startDate < todayKey()) return "Start date cannot be in the past."; if (days < 30 || days > 365) return "Challenge must be 30–365 days."; }
    if (step === 5) { if (num(draft.currentHifdhAmount) < 0 || num(draft.goalHifdhAmount) < 0) return "Qur'an amounts cannot be negative."; if (num(draft.goalHifdhAmount) && num(draft.goalHifdhAmount) < num(draft.currentHifdhAmount)) return "Target hifdh cannot be less than current hifdh."; }
    return "";
  }
  async function next() { const v = validate(); if (v) { setError(v); return; } setError(""); if (step < steps.length) await persist(step + 1); else await finish(); }
  async function skip() { setError(""); if (step < steps.length) await persist(step + 1); else await finish(); }
  async function finish() { const selectedPlans = draft.selectedPlans || { diet: "high_protein_med", exercise: "beginner_3day_full", quran: "steady_builder", selectedAt: new Date().toISOString(), names: { diet: choiceName("high_protein_med"), exercise: choiceName("beginner_3day_full"), quran: choiceName("steady_builder") } }; const nextDraft = { ...draft, selectedPlans, calorieTarget: String(bodyPlan.dailyTarget), stepTarget: String(bodyPlan.dailySteps), waterTarget: String(bodyPlan.dailyWaterCups), workoutDays: String(bodyPlan.exerciseDaysPerWeek), workoutMinutes: String(bodyPlan.exerciseMinPerSession), dailyMemorizeGoal: String(Math.round(quranPlan.newPerDay * 10) / 10), dailyReviewGoal: String(quranPlan.murajaaPerDay), quranTargets: { newPerDay: Math.round(quranPlan.newPerDay * 10) / 10, reviewPerDay: quranPlan.murajaaPerDay, murajaaCycleDays: quranPlan.murajaaCycleDays }, coachPlan: { bodyPlan, quranPlan } }; const supabase = createSupabaseBrowserClient(); await supabase.from("users").update({ onboarding_draft: nextDraft, onboarding_complete: false }).eq("id", userId); router.push("/plan-selection?from=onboarding"); }
  const first = safeFirstName(draft.name) || "friend";
  return <main className={pageBg}><div className="mx-auto max-w-4xl space-y-5"><section className="rounded-[2rem] bg-slate-950 p-6 text-white"><p className="text-sm font-bold text-emerald-300">Step {step} of {steps.length}</p><h1 className="mt-1 text-3xl font-black">{steps[step - 1]}</h1><p className="mt-2 text-sm font-bold text-slate-300">You can skip anything you do not know yet and edit it later.</p><div className="mt-4 grid gap-1" style={{ gridTemplateColumns: `repeat(${steps.length}, minmax(0, 1fr))` }}>{steps.map((_, i) => <div key={i} className={`h-2 rounded-full ${i < step ? "bg-emerald-400" : "bg-white/10"}`} />)}</div></section><section className={cardClass}>{step === 1 && <div className="text-center"><p className="text-lg font-black text-emerald-700">Bismillāh ar-Raḥmān ar-Raḥīm</p><h2 className="mt-4 text-3xl font-black">As-salāmu ʿalaykum, {first}.</h2><p className="mx-auto mt-4 max-w-2xl text-slate-600">Answer what you can. Skip what you do not know. You will pick your diet, exercise, and Qur'an plan before final confirmation.</p></div>}
{step === 2 && <div className="grid gap-4 md:grid-cols-2"><TextInput label="Age" type="number" min={13} max={100} value={draft.age} onChange={(v: string) => set("age", v)} /><label className="block"><span className="text-sm font-bold text-slate-700">Gender</span><select className={inputClass} value={draft.gender || ""} onChange={(e) => set("gender", e.target.value)}><option value="">Choose...</option><option>Male</option><option>Female</option><option>Prefer not to say</option></select></label><TextInput label="Current weight (lbs)" hint="Must be a realistic positive number." type="number" min={50} max={800} value={draft.currentWeightLbs} onChange={(v: string) => set("currentWeightLbs", v)} /><TextInput label="Goal weight (lbs)" hint="No negatives. You can adjust later." type="number" min={50} max={800} value={draft.goalWeightLbs} onChange={(v: string) => set("goalWeightLbs", v)} />{pace && <p className={`md:col-span-2 rounded-2xl p-4 font-bold ${pace.isFast ? "bg-amber-50 text-amber-900" : "bg-emerald-50 text-emerald-900"}`}>You want to {pace.kind === "loss" ? "lose" : pace.kind} about {Math.abs(pace.weekly)} lbs/week. {pace.isFast ? "That is fast, so the app will keep your targets safer." : "That pace looks reasonable."}</p>}</div>}
{step === 3 && <div className="grid gap-4 md:grid-cols-2"><TextInput label="Start date" type="date" min={todayKey()} value={draft.startDate} onChange={(v: string) => set("startDate", v < todayKey() ? todayKey() : v)} /><TextInput label="End date" type="date" min={draft.startDate || todayKey()} value={draft.endDate} onChange={(v: string) => set("endDate", v)} /><div className="md:col-span-2 flex flex-wrap gap-2">{[30, 60, 90, 180].map((d) => <Pill key={d} active={days === d} onClick={() => { const start = draft.startDate && draft.startDate >= todayKey() ? draft.startDate : todayKey(); set("startDate", start); set("endDate", plusDays(start, d)); }}>{d} days</Pill>)}</div><p className="md:col-span-2 rounded-2xl bg-slate-50 p-4 font-bold">{days ? `Your challenge is ${days} days. You need about ${(100 / days).toFixed(1)} points/day.` : "Choose dates to see your daily pace."}</p></div>}
{step === 4 && <div className="space-y-5"><p className="rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-700">Pick your current activity level. Your target workout plan is chosen later.</p><div className="flex flex-wrap gap-2">{["Sedentary", "Light", "Moderate", "Active"].map((level) => <Pill key={level} active={(draft.activityLevel || "Moderate") === level} onClick={() => set("activityLevel", level)}>{level}</Pill>)}</div><div className="rounded-[1.5rem] bg-slate-950 p-5 text-white"><p className="text-sm font-black text-emerald-300">Body targets preview</p><p className="mt-2 font-black">{bodyPlan.dailyTarget} kcal • {bodyPlan.dailySteps.toLocaleString()} steps • {bodyPlan.dailyWaterCups} cups water</p></div></div>}
{step === 5 && <div className="space-y-5"><p className="rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-700">Current hifdh is what you know today. Target hifdh is what you want to know by the end. Target cannot be lower than current.</p><div className="grid gap-4 md:grid-cols-2"><label><span className="text-sm font-bold text-slate-700">Units</span><select className={inputClass} value={draft.measurementUnit || "pages"} onChange={(e) => set("measurementUnit", e.target.value)}><option>lines</option><option>pages</option><option>surahs</option><option>juz</option></select></label><TextInput label={`Current hifdh (${draft.measurementUnit || "pages"})`} type="number" min={0} value={draft.currentHifdhAmount} onChange={(v: string) => set("currentHifdhAmount", v)} /><TextInput label={`Target hifdh (${draft.measurementUnit || "pages"})`} hint={`Must be ${num(draft.currentHifdhAmount)} or higher.`} type="number" min={num(draft.currentHifdhAmount)} value={draft.goalHifdhAmount} onChange={(v: string) => set("goalHifdhAmount", v)} /><label><span className="text-sm font-bold text-slate-700">Murajaa cycle</span><select className={inputClass} value={draft.murajaaCycleDays || "10"} onChange={(e) => set("murajaaCycleDays", e.target.value)}><option value="5">5 days</option><option value="7">7 days</option><option value="10">10 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label></div><p className="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-900">Murajaa cycle means how many days it takes to review everything you know. Example: 30 pages over 10 days = about 3 pages/day.</p><div className="rounded-[1.5rem] bg-slate-950 p-5 text-white"><p className="text-sm font-black text-emerald-300">Qur'an preview</p><p className="mt-2 font-black">{quranPlan.memorizationSchedule} • Review {quranPlan.murajaaPerDay} {quranPlan.unit}/day</p></div></div>}
{step === 6 && <div className="space-y-4"><p className="rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-700">Pick two personal goals. Make each task specific so it is easy to log.</p><TextInput label="Goal 1" value={draft.goal1} onChange={(v: string) => set("goal1", v)} /><TextInput label="Goal 1 daily task" value={draft.goal1Task} onChange={(v: string) => set("goal1Task", v)} /><TextInput label="Goal 2" value={draft.goal2} onChange={(v: string) => set("goal2", v)} /><TextInput label="Goal 2 daily task" value={draft.goal2Task} onChange={(v: string) => set("goal2Task", v)} /></div>}
{step === 7 && <div className="space-y-4"><p className="rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-700">Limits are optional. Leave a box blank to skip it.</p>{["spendingLimit", "restaurantLimit", "screenLimit", "youtubeLimit"].map((key) => <TextInput key={key} label={key === "spendingLimit" ? "Spending money limit" : key === "restaurantLimit" ? "Restaurant visits limit" : key === "screenLimit" ? "Screen time hours/day" : "YouTube hours/day"} type="number" min={0} value={draft[key]} onChange={(v: string) => set(key, v)} />)}</div>}
{step === 8 && <div className="space-y-6"><p className="rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-700">Choose one plan in each category before the final preview. These choices will appear on your dashboard and log page.</p><PlanPick title="Diet" value={draft.selectedPlans?.diet || ""} choices={["high_protein_med", "calorie_counting", "dash_whole_food"]} setChoice={(id: string) => set("selectedPlans", { ...(draft.selectedPlans || {}), diet: id, names: { ...(draft.selectedPlans?.names || {}), diet: choiceName(id) } })} /><PlanPick title="Exercise" value={draft.selectedPlans?.exercise || ""} choices={["beginner_3day_full", "upper_lower_4day", "walk_bodyweight"]} setChoice={(id: string) => set("selectedPlans", { ...(draft.selectedPlans || {}), exercise: id, names: { ...(draft.selectedPlans?.names || {}), exercise: choiceName(id) } })} /><PlanPick title="Qur'an" value={draft.selectedPlans?.quran || ""} choices={["steady_builder", "reviewer", "maintainer"]} setChoice={(id: string) => set("selectedPlans", { ...(draft.selectedPlans || {}), quran: id, names: { ...(draft.selectedPlans?.names || {}), quran: choiceName(id) } })} /></div>}
{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="mt-6 flex flex-wrap justify-between gap-3"><button onClick={() => setStep(Math.max(1, step - 1))} className="rounded-full bg-slate-100 px-5 py-3 font-bold">Back</button><button onClick={skip} className="rounded-full bg-white px-5 py-3 font-black text-slate-700 ring-1 ring-slate-200">Skip for now</button><button onClick={next} className="rounded-full bg-emerald-600 px-5 py-3 font-black text-white">{step < steps.length ? "Next" : "Preview my plan"}</button></div></section></div></main>;
}
function PlanPick({ title, choices, value, setChoice }: any) { return <div><p className="mb-2 text-sm font-black text-emerald-700">{title}</p><div className="flex flex-wrap gap-2">{choices.map((id: string) => <Pill key={id} active={value === id} onClick={() => setChoice(id)}>{choiceName(id)}</Pill>)}</div></div>; }
