"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { BottomNav } from "@/components/BottomNav";
import { cardClass, inputClass, isChallengeStartedFromProfile, pageBg } from "@/lib/challenge-ui";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { ensureUserRecord } from "@/lib/supabase/ensure-user-record";
import { MissionPanel } from "./mission-panel";

type EntryCategory = "calories" | "water" | "steps" | "exercise" | "quranMemorized" | "quranReviewed" | "money" | "screen";
type Entry = { id: number; label: string; amount: number; note?: string; points?: number };
type EntryState = Record<EntryCategory, Entry[]>;
type SalahState = Record<"Fajr" | "Dhuhr" | "Asr" | "Maghrib" | "Isha", boolean>;

const PRAYERS: Array<keyof SalahState> = ["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"];
const emptyEntries: EntryState = { calories: [], water: [], steps: [], exercise: [], quranMemorized: [], quranReviewed: [], money: [], screen: [] };
const defaultSalah: SalahState = { Fajr: false, Dhuhr: false, Asr: false, Maghrib: false, Isha: false };
const defaultSleep = { hours: "", bedtime: "", wake: "" };
const defaultGoals = { goal1: "", goal2: "" };
const defaultReflection = { mood: "", notes: "", slipped: "", wentWell: "" };
const MOODS = [{ v: "1", label: "Hard" }, { v: "2", label: "Low" }, { v: "3", label: "Okay" }, { v: "4", label: "Good" }, { v: "5", label: "Great" }];

function todayKey() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
function safeNum(v: unknown, fallback = 0) { const n = Number(v); return Number.isFinite(n) ? n : fallback; }
function target(v: unknown, fallback: number) { const n = safeNum(v, fallback); return n > 0 ? n : fallback; }
function round3(n: number) { return Math.round(n * 1000) / 1000; }
function capRatio(amount: number, goal: number) { return !amount || !goal || goal <= 0 ? 0 : Math.max(0, Math.min(1, amount / goal)); }
function sum(list: Entry[] = []) { return list.reduce((s, e) => s + safeNum(e.amount), 0); }
function sumPoints(list: Entry[] = []) { return list.reduce((s, e) => s + safeNum(e.points), 0); }
function daysBetween(start?: string, end?: string) { if (!start || !end) return 90; const s = new Date(`${String(start).slice(0, 10)}T00:00:00`); const e = new Date(`${String(end).slice(0, 10)}T00:00:00`); return Math.max(1, Math.floor((e.getTime() - s.getTime()) / 86400000) + 1); }
function percent(current: number, goal: number) { return Math.max(0, Math.min(100, Math.round((current / Math.max(1, goal)) * 100))); }
function fmt(n: number) { return Math.round(n).toLocaleString(); }
function nextPrayer(salah: SalahState) { return PRAYERS.find((p) => !salah[p]) || "Fajr"; }
function cleanReflection(raw: any) { const keepText = (v: unknown) => { const t = typeof v === "string" ? v : ""; return /^[1-5]$/.test(t.trim()) ? "" : t; }; const mood = /^[1-5]$/.test(String(raw?.mood || "")) ? String(raw.mood) : ""; return { mood, notes: keepText(raw?.notes), wentWell: keepText(raw?.wentWell), slipped: keepText(raw?.slipped) }; }
function localSaved(row: any) { if (!row) return null; return { entries: { ...emptyEntries, ...(row.entries || {}) }, salah: { ...defaultSalah, ...(row.salah || {}) }, sleep: row.sleep || defaultSleep, goals: row.goals || defaultGoals, reflection: cleanReflection(row.reflection || defaultReflection), weight: row.weight ? String(row.weight) : "", computedPoints: row.computed_points || row.computedPoints || { total: 0 } }; }
function aggregatePillars(rows: Array<{ computed_points?: any; computedPoints?: any }>) { const pillars = rows.reduce((a, row) => { const p = row.computed_points || row.computedPoints || {}; a.quwwah += safeNum(p.body); a.imaan += safeNum(p.quran); a.sabr += safeNum(p.discipline); a.niyyah += safeNum(p.personal); a.adab += safeNum(p.character); return a; }, { quwwah: 0, imaan: 0, sabr: 0, niyyah: 0, adab: 0 }); Object.keys(pillars).forEach((k) => (pillars as any)[k] = round3((pillars as any)[k])); const total = round3(Object.values(pillars).reduce((s: number, v: any) => s + safeNum(v), 0)); return { pillars, total }; }

export default function CheckInMain() {
  const router = useRouter();
  const [draft, setDraft] = useState<Record<string, any>>({});
  const [userId, setUserId] = useState("");
  const [entries, setEntries] = useState<EntryState>(emptyEntries);
  const [salah, setSalah] = useState<SalahState>(defaultSalah);
  const [sleep, setSleep] = useState(defaultSleep);
  const [goals, setGoals] = useState(defaultGoals);
  const [reflection, setReflection] = useState(defaultReflection);
  const [weight, setWeight] = useState("");
  const [computedTotal, setComputedTotal] = useState(0);
  const [open, setOpen] = useState("quwwah");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const date = todayKey();

  useEffect(() => { async function load() { const supabase = createSupabaseBrowserClient(); const { data } = await supabase.auth.getUser(); if (!data.user) { router.push("/login"); return; } const record = await ensureUserRecord(data.user); const d = (record.onboarding_draft || {}) as Record<string, any>; setDraft(d); setUserId(record.id); const { data: row } = await supabase.from("daily_logs").select("*").eq("user_id", record.id).eq("date", date).maybeSingle(); const saved = localSaved(row) || d.checkins?.[date]; if (saved) { setEntries({ ...emptyEntries, ...(saved.entries || {}) }); setSalah({ ...defaultSalah, ...(saved.salah || {}) }); setSleep(saved.sleep || defaultSleep); setGoals(saved.goals || defaultGoals); setReflection(cleanReflection(saved.reflection || defaultReflection)); setWeight(saved.weight || ""); setComputedTotal(safeNum(saved.computedPoints?.total)); } setLoading(false); } load(); }, [router, date]);

  const goalsTarget = { calories: target(draft.calorieTarget, 2200), water: target(draft.waterTarget, 8), steps: target(draft.stepTarget, 10000), exercise: target(draft.workoutMinutes, 45), memorize: target(draft.dailyMemorizeGoal || draft.quranDailyTarget, 1), review: target(draft.dailyReviewGoal || draft.quranReviewTarget, 1), spendingDaily: Math.max(1, target(draft.spendingLimit, 300) / 30), screen: target(draft.screenLimit, 3) };
  const totals = useMemo(() => ({ calories: sum(entries.calories), water: sum(entries.water), steps: sum(entries.steps), exercise: sum(entries.exercise), quranMemorized: sum(entries.quranMemorized), quranReviewed: sum(entries.quranReviewed), money: sum(entries.money), screen: sum(entries.screen) }), [entries]);
  const dailyMax = () => 100 / daysBetween(draft.startDate, draft.endDate);

  function entryGain(category: EntryCategory, amount: number) { const dMax = dailyMax(); const body = dMax * 0.28; const imaan = dMax * 0.24; const sabr = dMax * 0.18; const map: Record<EntryCategory, { max: number; slice: number; target: number; limit?: boolean }> = { calories: { max: body, slice: 0.25, target: goalsTarget.calories }, water: { max: body, slice: 0.25, target: goalsTarget.water }, steps: { max: body, slice: 0.2, target: goalsTarget.steps }, exercise: { max: body, slice: 0.2, target: goalsTarget.exercise }, quranMemorized: { max: imaan, slice: 0.35, target: goalsTarget.memorize }, quranReviewed: { max: imaan, slice: 0.3, target: goalsTarget.review }, money: { max: sabr, slice: 0.15, target: goalsTarget.spendingDaily, limit: true }, screen: { max: sabr, slice: 0.25, target: goalsTarget.screen, limit: true } }; const c = map[category]; const ratio = c.limit ? Math.min(0.25, capRatio(amount, c.target)) : capRatio(amount, c.target); return round3(c.max * c.slice * ratio); }
  function prayerGain() { return round3(dailyMax() * 0.24 * 0.35 * (1 / 5)); }
  function computeDay(nextEntries = entries, nextSalah = salah, nextReflection = reflection) { const body = sumPoints(nextEntries.calories) + sumPoints(nextEntries.water) + sumPoints(nextEntries.steps) + sumPoints(nextEntries.exercise); const quran = sumPoints(nextEntries.quranMemorized) + sumPoints(nextEntries.quranReviewed) + PRAYERS.filter((p) => nextSalah[p]).length * prayerGain(); const discipline = sumPoints(nextEntries.money) + sumPoints(nextEntries.screen); const personal = (goals.goal1 === "done" ? dailyMax() * 0.1 : goals.goal1 === "partial" ? dailyMax() * 0.05 : 0) + (goals.goal2 === "done" ? dailyMax() * 0.1 : goals.goal2 === "partial" ? dailyMax() * 0.05 : 0); const character = nextReflection.mood || nextReflection.wentWell || nextReflection.slipped ? dailyMax() * 0.025 : 0; return { body: round3(body), quran: round3(quran), discipline: round3(discipline), personal: round3(personal), character: round3(character), total: round3(body + quran + discipline + personal + character), totals }; }

  async function persist(nextEntries = entries, nextSalah = salah, msg = "Saved", gain = 0, nextReflection = reflection) { if (!userId) return; if (!isChallengeStartedFromProfile(draft)) { setError("Your challenge has not started yet. Check-ins unlock on your selected start date."); return; } const clean = cleanReflection(nextReflection); const computedPoints = computeDay(nextEntries, nextSalah, clean); setComputedTotal(computedPoints.total); setSaving(true); setError(""); const supabase = createSupabaseBrowserClient(); const payload = { entries: nextEntries, sleep, goals, salah: nextSalah, reflection: clean, weight, computedPoints, updatedAt: new Date().toISOString(), localDate: date }; const { error: logError } = await supabase.from("daily_logs").upsert({ user_id: userId, date, entries: nextEntries, weight: weight ? Number(weight) : null, sleep, goals, salah: nextSalah, reflection: clean, computed_points: computedPoints }, { onConflict: "user_id,date" }); const { data: allLogs } = await supabase.from("daily_logs").select("computed_points").eq("user_id", userId); const fromDb = aggregatePillars((allLogs || []) as any[]); const checkins = { ...(draft.checkins || {}), [date]: payload }; const nextDraft = { ...draft, checkins, current_score: fromDb.total, pillar_scores: fromDb.pillars }; const { error: userError } = await supabase.from("users").update({ onboarding_draft: nextDraft, current_score: fromDb.total, pillar_scores: fromDb.pillars }).eq("id", userId); setSaving(false); if (logError || userError) { setError((logError || userError)?.message || "Save failed."); return; } setDraft(nextDraft); setReflection(clean); setMessage(gain > 0 ? `${msg} • +${gain.toFixed(3)} pts • ${computedPoints.total.toFixed(3)} today` : `${msg} • ${computedPoints.total.toFixed(3)} today`); setTimeout(() => setMessage(""), 2400); }

  function addEntry(category: EntryCategory, label: string, amount: number, note = "") { if (!amount || amount <= 0) return; const gain = entryGain(category, amount); const nextEntries = { ...entries, [category]: [...entries[category], { id: Date.now(), label, amount, note, points: gain }] }; setEntries(nextEntries); persist(nextEntries, salah, `${label} saved`, gain); }
  function markPrayer(p?: keyof SalahState) { const prayer = p || nextPrayer(salah); const next = { ...salah, [prayer]: !salah[prayer] }; setSalah(next); persist(entries, next, `${prayer} saved`, !salah[prayer] ? prayerGain() : 0); }
  function saveGoal(slot: "goal1" | "goal2", value: string) { const next = { ...goals, [slot]: value }; setGoals(next); setTimeout(() => persist(entries, salah, "Goal saved", value === "done" ? dailyMax() * 0.1 : value === "partial" ? dailyMax() * 0.05 : 0), 0); }

  const bodyProgress = Math.round((percent(totals.calories, goalsTarget.calories) + percent(totals.water, goalsTarget.water) + percent(totals.steps, goalsTarget.steps) + percent(totals.exercise, goalsTarget.exercise)) / 4);
  const faithProgress = Math.round(((PRAYERS.filter((p) => salah[p]).length / 5) * 100 + percent(totals.quranMemorized, goalsTarget.memorize) + percent(totals.quranReviewed, goalsTarget.review)) / 3);
  const sabrEngaged = entries.money.length + entries.screen.length > 0;
  const disciplineProgress = sabrEngaged ? Math.round((Math.max(0, 100 - percent(totals.money, goalsTarget.spendingDaily)) + Math.max(0, 100 - percent(totals.screen, goalsTarget.screen))) / 2) : 0;

  if (loading) return <main className={pageBg}><section className={`${cardClass} mx-auto max-w-xl`}>Loading today…</section><BottomNav /></main>;
  return <main className={pageBg}><div className="mx-auto max-w-5xl space-y-5"><section className="rounded-[2rem] bg-slate-950 p-6 text-white"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold text-emerald-300">Log Today</p><h1 className="mt-1 text-4xl font-black">{computedTotal.toFixed(3)} pts today</h1><p className="mt-2 text-slate-300">Every Save entry adds proportional points from that target.</p></div><div className="grid grid-cols-3 gap-2 text-center"><HeroStat label="Today: Body" value={`${bodyProgress}%`} /><HeroStat label="Today: Faith" value={`${faithProgress}%`} /><HeroStat label="Today: Sabr" value={`${disciplineProgress}%`} /></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><QuickAction label={`+1 cup water (+${entryGain("water", 1).toFixed(3)})`} primary onClick={() => addEntry("water", "+1 cup water", 1)} /><QuickAction label={`+1k steps (+${entryGain("steps", 1000).toFixed(3)})`} onClick={() => addEntry("steps", "+1k steps", 1000)} /><QuickAction label={`+10 min exercise (+${entryGain("exercise", 10).toFixed(3)})`} onClick={() => addEntry("exercise", "+10 min movement", 10)} /><QuickAction label={`Mark ${nextPrayer(salah)} (+${prayerGain().toFixed(3)})`} onClick={() => markPrayer()} /></div></section>{saving && <p className="rounded-xl bg-slate-50 p-3 text-sm font-bold text-slate-700">Saving…</p>}{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</p>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}
    <Accordion id="quwwah" open={open} setOpen={setOpen} title="QUWWAH — Body" progress={bodyProgress} summary={`${fmt(totals.calories)}/${fmt(goalsTarget.calories)} cal • ${fmt(totals.water)}/${fmt(goalsTarget.water)} cups • ${fmt(totals.steps)}/${fmt(goalsTarget.steps)} steps`}><div className="grid gap-4 md:grid-cols-2"><EntryBox title="Calories" current={totals.calories} target={goalsTarget.calories} unit="cal" labels={["Breakfast", "Lunch", "Dinner", "Snack"]} pointPreview={(a) => entryGain("calories", a)} onSave={(l, a, n) => addEntry("calories", l, a, n)} /><EntryBox title="Water" current={totals.water} target={goalsTarget.water} unit="cups" labels={["Cup", "Bottle", "Before meal"]} pointPreview={(a) => entryGain("water", a)} onSave={(l, a, n) => addEntry("water", l, a, n)} /><EntryBox title="Steps" current={totals.steps} target={goalsTarget.steps} unit="steps" labels={["Morning", "Afternoon", "Walk"]} pointPreview={(a) => entryGain("steps", a)} onSave={(l, a, n) => addEntry("steps", l, a, n)} /><EntryBox title="Exercise" current={totals.exercise} target={goalsTarget.exercise} unit="min" labels={["Walking", "Gym", "Boxing"]} pointPreview={(a) => entryGain("exercise", a)} onSave={(l, a, n) => addEntry("exercise", l, a, n)} /></div></Accordion>
    <Accordion id="imaan" open={open} setOpen={setOpen} title="IMAAN — Faith" progress={faithProgress} summary={`${PRAYERS.filter((p) => salah[p]).length}/5 salah • ${totals.quranMemorized}/${goalsTarget.memorize} new • ${totals.quranReviewed}/${goalsTarget.review} review`}><div className="grid gap-4 md:grid-cols-2"><EntryBox title="Qur'an memorized" current={totals.quranMemorized} target={goalsTarget.memorize} unit={draft.measurementUnit || "units"} labels={["After Fajr", "After Maghrib", "Before sleep"]} pointPreview={(a) => entryGain("quranMemorized", a)} onSave={(l, a, n) => addEntry("quranMemorized", l, a, n)} /><EntryBox title="Qur'an reviewed" current={totals.quranReviewed} target={goalsTarget.review} unit={draft.measurementUnit || "units"} labels={["Murajaa", "Old review", "New review"]} pointPreview={(a) => entryGain("quranReviewed", a)} onSave={(l, a, n) => addEntry("quranReviewed", l, a, n)} /><div className="md:col-span-2 grid gap-2 md:grid-cols-5">{PRAYERS.map((p) => <button key={p} onClick={() => markPrayer(p)} className={`rounded-xl p-3 text-sm font-bold ${salah[p] ? "bg-emerald-100 text-emerald-900" : "bg-slate-50 text-slate-700"}`}>{salah[p] ? "Done " : ""}{p} {salah[p] ? "" : `+${prayerGain().toFixed(3)}`}</button>)}</div></div></Accordion>
    <Accordion id="sabr" open={open} setOpen={setOpen} title="SABR — Discipline" progress={disciplineProgress} summary={sabrEngaged ? `$${totals.money}/${goalsTarget.spendingDaily.toFixed(0)} daily pace • ${totals.screen}/${goalsTarget.screen}h screen` : "Not logged yet • discipline starts after you check in"}><div className="grid gap-4 md:grid-cols-2"><EntryBox title="Money spent" current={totals.money} target={goalsTarget.spendingDaily} unit="$" labels={["Food", "Gas", "School", "Other"]} pointPreview={(a) => entryGain("money", a)} onSave={(l, a, n) => addEntry("money", l, a, n)} /><EntryBox title="Screen time" current={totals.screen} target={goalsTarget.screen} unit="hours" labels={["Social", "YouTube", "Reels", "TV"]} pointPreview={(a) => entryGain("screen", a)} onSave={(l, a, n) => addEntry("screen", l, a, n)} /></div></Accordion>
    <Accordion id="niyyah" open={open} setOpen={setOpen} title="NIYYAH — Mission" progress={goals.goal1 || goals.goal2 ? 50 : 0} summary={`${draft.goal1 || "Goal 1"}: ${goals.goal1 || "not logged"} • ${draft.goal2 || "Goal 2"}: ${goals.goal2 || "not logged"}`}><div className="space-y-4"><MissionPanel embedded /><div className="grid gap-4 md:grid-cols-2"><GoalBox title={draft.goal1 || "Personal Goal 1"} task={draft.goal1Task || "Your first daily task"} value={goals.goal1} onChange={(v) => saveGoal("goal1", v)} /><GoalBox title={draft.goal2 || "Personal Goal 2"} task={draft.goal2Task || "Your second daily task"} value={goals.goal2} onChange={(v) => saveGoal("goal2", v)} /></div></div></Accordion>
    <Accordion id="adab" open={open} setOpen={setOpen} title="ADAB — Character" progress={reflection.mood ? 60 : 0} summary={reflection.mood ? `Mood ${reflection.mood}/5 • reflection saved` : "Reflect before bed"}><div className="space-y-4"><div className="flex flex-wrap gap-2">{MOODS.map((m) => <button key={m.v} onClick={() => { const next = cleanReflection({ ...reflection, mood: m.v }); setReflection(next); persist(entries, salah, "Mood saved", dailyMax() * 0.025, next); }} className={`rounded-2xl px-5 py-3 text-lg font-black ${reflection.mood === m.v ? "bg-emerald-500 text-white" : "bg-slate-100 text-slate-700"}`}>{m.label}</button>)}</div><textarea className={inputClass} rows={3} placeholder="What went well?" value={reflection.wentWell} onChange={(e) => setReflection(cleanReflection({ ...reflection, wentWell: e.target.value }))} onBlur={() => persist(entries, salah, "Reflection saved")} /><textarea className={inputClass} rows={3} placeholder="What slipped?" value={reflection.slipped} onChange={(e) => setReflection(cleanReflection({ ...reflection, slipped: e.target.value }))} onBlur={() => persist(entries, salah, "Reflection saved")} /></div></Accordion>
    <div className="flex justify-center"><button onClick={() => persist(entries, salah, "Today finalized")} className="rounded-full bg-emerald-600 px-6 py-3 font-black text-white shadow-xl">Finalize today</button></div></div><BottomNav /></main>;
}

function HeroStat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/10 px-4 py-3"><p className="text-xs font-bold text-slate-300">{label}</p><p className="text-lg font-black text-white">{value}</p></div>; }
function QuickAction({ label, onClick, primary = false }: { label: string; onClick: () => void; primary?: boolean }) { return <button onClick={onClick} className={`rounded-2xl px-4 py-3 text-sm font-black ${primary ? "bg-emerald-400 text-slate-950" : "bg-white/10 text-white"}`}>{label}</button>; }
function ProgressBar({ value }: { value: number }) { return <div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500 transition-all" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }
function Accordion({ id, open, setOpen, title, summary, progress = 0, children }: { id: string; open: string; setOpen: (id: string) => void; title: string; summary: string; progress?: number; children: ReactNode }) { const isOpen = open === id; return <section className={cardClass}><button onClick={() => setOpen(isOpen ? "" : id)} className="flex w-full items-start justify-between gap-4 text-left"><div className="flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-black text-slate-950">{title}</h2><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">{progress}%</span></div><p className="mt-1 text-sm font-bold text-slate-500">{summary}</p><ProgressBar value={progress} /></div><span className="text-2xl font-black text-emerald-700">{isOpen ? "⌄" : "›"}</span></button>{isOpen && <div className="mt-5">{children}</div>}</section>; }
function quickAmounts(unit: string) { if (unit === "cups") return [1, 2, 3]; if (unit === "steps") return [1000, 2500, 5000]; if (unit === "cal") return [200, 500, 800]; if (unit === "min") return [10, 30, 45]; if (unit === "$" ) return [5, 10, 20]; if (unit === "hours") return [0.25, 0.5, 1]; return [1, 2, 3]; }
function EntryBox({ title, current, target, unit, labels, onSave, pointPreview }: { title: string; current: number; target: number; unit: string; labels: string[]; onSave: (label: string, amount: number, note: string) => void; pointPreview: (amount: number) => number }) { const [label, setLabel] = useState(labels[0]); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const amt = Number(amount); const gain = amt > 0 ? pointPreview(amt) : 0; return <div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-black">{title}</h3><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-emerald-700">{fmt(current)} / {fmt(target)} {unit}</span></div><ProgressBar value={percent(current, target)} /><div className="mt-3 flex flex-wrap gap-2">{quickAmounts(unit).map((v) => <button type="button" key={v} onClick={() => setAmount(String(v))} className={`rounded-full px-3 py-1 text-xs font-black ${Number(amount) === v ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`}>+{fmt(v)}</button>)}</div><div className="mt-3 grid gap-2 md:grid-cols-2"><select className={inputClass} value={label} onChange={(e) => setLabel(e.target.value)}>{labels.map((x) => <option key={x}>{x}</option>)}</select><input className={inputClass} type="number" value={amount} placeholder={`Add ${unit}`} onChange={(e) => setAmount(e.target.value)} /></div><input className={`${inputClass} mt-2`} placeholder="Optional note" value={note} onChange={(e) => setNote(e.target.value)} /><button disabled={!amt || amt <= 0} onClick={() => { onSave(label, amt, note); setAmount(""); setNote(""); }} className="mt-3 rounded-full bg-emerald-600 px-4 py-2 text-sm font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300">Save entry • +{gain.toFixed(3)} pts</button></div>; }
function GoalBox({ title, task, value, onChange }: { title: string; task: string; value: string; onChange: (value: string) => void }) { return <div className="rounded-2xl bg-slate-50 p-4"><h3 className="text-xl font-black">{title}</h3><p className="mt-1 text-sm font-bold text-slate-600">{task}</p><div className="mt-4 flex flex-wrap gap-2">{["done", "partial", "missed"].map((v) => <button key={v} onClick={() => onChange(v)} className={`rounded-full px-4 py-2 text-sm font-black ${value === v ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`}>{v}</button>)}</div></div>; }
