"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { BottomNav } from "@/components/BottomNav";
import { cardClass, inputClass, isChallengeStartedFromProfile, pageBg } from "@/lib/challenge-ui";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { ensureUserRecord } from "@/lib/supabase/ensure-user-record";
import { aggregateCheckInScores, computePointsFromSavedCheckIn } from "@/lib/scoring";

type Entry = { id: number; label: string; amount: number; note?: string };
type EntryState = { calories: Entry[]; water: Entry[]; steps: Entry[]; exercise: Entry[]; quranMemorized: Entry[]; quranReviewed: Entry[]; money: Entry[]; screen: Entry[] };
type EntrySaveHandler = (label: string, amount: number, note: string) => void;
type EntryBoxProps = { title: string; current: number; target: number; unit: string; labels: string[]; onSave: EntrySaveHandler; helper?: string };
type AccordionProps = { id: string; open: string; setOpen: (id: string) => void; title: string; summary: string; progress?: number; children: React.ReactNode };
type GoalBoxProps = { title: string; task: string; value: string; onChange: (value: string) => void };

const PRAYERS = ["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"] as const;
const emptyEntries: EntryState = { calories: [], water: [], steps: [], exercise: [], quranMemorized: [], quranReviewed: [], money: [], screen: [] };

function localDateKey() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
function sum(entries: Entry[]) { return (entries || []).reduce((total, entry) => total + (Number(entry.amount) || 0), 0); }
function totals(entries: EntryState) { return { calories: sum(entries.calories), water: sum(entries.water), steps: sum(entries.steps), exercise: sum(entries.exercise), quranMemorized: sum(entries.quranMemorized), quranReviewed: sum(entries.quranReviewed), money: sum(entries.money), screen: sum(entries.screen) }; }
function normalize(row: any) { if (!row) return null; return { entries: row.entries || emptyEntries, weight: row.weight ? String(row.weight) : "", sleep: row.sleep || { hours: "", bedtime: "", wake: "" }, goals: row.goals || { goal1: "", goal2: "" }, salah: { Fajr: false, Dhuhr: false, Asr: false, Maghrib: false, Isha: false, ...(row.salah || {}) }, reflection: row.reflection || { mood: "", notes: "", slipped: "", wentWell: "" }, computedPoints: row.computed_points || row.computedPoints || { total: 0 } }; }
function targetNumber(value: any, fallback: number) { const n = Number(value); return Number.isFinite(n) && n > 0 ? n : fallback; }
function todayWorkout(draft: Record<string, any>) { const plan = draft.coachPlan?.workoutPlan || []; const day = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][new Date().getDay()]; return plan.find((x: any) => x.day === day)?.name || "today's movement"; }
function pct(current: number, target: number) { if (!target) return 0; return Math.max(0, Math.min(100, Math.round((current / target) * 100))); }
function nextPrayer(salah: Record<string, boolean>) { return PRAYERS.find((p) => !salah[p]) || PRAYERS[0]; }

export default function CheckInMain() {
  const router = useRouter();
  const [draft, setDraft] = useState<Record<string, any>>({});
  const [userId, setUserId] = useState("");
  const [entries, setEntries] = useState<EntryState>(emptyEntries);
  const [weight, setWeight] = useState("");
  const [sleep, setSleep] = useState({ hours: "", bedtime: "", wake: "" });
  const [goals, setGoals] = useState({ goal1: "", goal2: "" });
  const [salah, setSalah] = useState({ Fajr: false, Dhuhr: false, Asr: false, Maghrib: false, Isha: false });
  const [reflection, setReflection] = useState({ mood: "", notes: "", slipped: "", wentWell: "" });
  const [computedTotal, setComputedTotal] = useState(0);
  const [open, setOpen] = useState("quwwah");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const today = localDateKey();

  useEffect(() => { async function load() { const supabase = createSupabaseBrowserClient(); const { data } = await supabase.auth.getUser(); if (!data.user) { router.push("/login"); return; } const record = await ensureUserRecord(data.user); const loadedDraft = (record.onboarding_draft || {}) as Record<string, any>; setDraft(loadedDraft); setUserId(data.user.id); const { data: row } = await supabase.from("daily_logs").select("*").eq("user_id", data.user.id).eq("date", today).maybeSingle(); const saved = normalize(row) || loadedDraft.checkins?.[today]; if (saved) { setEntries(saved.entries || emptyEntries); setWeight(saved.weight || ""); setSleep(saved.sleep || { hours: "", bedtime: "", wake: "" }); setGoals(saved.goals || { goal1: "", goal2: "" }); setSalah({ Fajr: false, Dhuhr: false, Asr: false, Maghrib: false, Isha: false, ...(saved.salah || {}) }); setReflection(saved.reflection || { mood: "", notes: "", slipped: "", wentWell: "" }); setComputedTotal(Number(saved.computedPoints?.total || 0)); } setLoading(false); } load(); }, [router, today]);

  const t = useMemo(() => totals(entries), [entries]);
  const targets = { calories: targetNumber(draft.calorieTarget, 2200), water: targetNumber(draft.waterTarget, 8), steps: targetNumber(draft.stepTarget, 10000), exercise: targetNumber(draft.workoutMinutes, 45), memorize: targetNumber(draft.dailyMemorizeGoal, 1), review: targetNumber(draft.dailyReviewGoal, 1), screen: targetNumber(draft.screenLimit, 3), spending: targetNumber(draft.spendingLimit, 300) };
  const bodyProgress = Math.round((pct(t.calories, targets.calories) + pct(t.water, targets.water) + pct(t.steps, targets.steps) + pct(t.exercise, targets.exercise)) / 4);
  const faithProgress = Math.round(((PRAYERS.filter((p) => (salah as any)[p]).length / 5) * 100 + pct(t.quranMemorized, targets.memorize) + pct(t.quranReviewed, targets.review)) / 3);
  const disciplineProgress = Math.round((Math.max(0, 100 - pct(t.money, targets.spending)) + Math.max(0, 100 - pct(t.screen, targets.screen))) / 2);

  async function save(next?: Partial<{ entries: EntryState; weight: string; sleep: typeof sleep; goals: typeof goals; salah: typeof salah; reflection: typeof reflection }>, msg = "Saved") {
    if (!userId) return;
    if (!isChallengeStartedFromProfile(draft)) { setError("Your challenge has not started yet. Check-ins unlock on your selected start date."); return; }
    setSaving(true); setError("");
    const supabase = createSupabaseBrowserClient();
    const nextEntries = next?.entries || entries;
    const entryTotals = totals(nextEntries);
    const base = { entries: nextEntries, weight: next?.weight ?? weight, sleep: next?.sleep || sleep, goals: next?.goals || goals, salah: next?.salah || salah, reflection: next?.reflection || reflection, updatedAt: new Date().toISOString(), localDate: today };
    const raw = computePointsFromSavedCheckIn(draft, base);
    const computedPoints = { ...raw, totals: entryTotals };
    const payload = { ...base, computedPoints };
    const { error: logError } = await supabase.from("daily_logs").upsert({ user_id: userId, date: today, entries: payload.entries, weight: payload.weight ? Number(payload.weight) : null, sleep: payload.sleep, goals: payload.goals, salah: payload.salah, reflection: payload.reflection, computed_points: computedPoints }, { onConflict: "user_id,date" });
    const nextDraftWithoutAggregate = { ...draft, checkins: { ...(draft.checkins || {}), [today]: payload } };
    const aggregate = aggregateCheckInScores(nextDraftWithoutAggregate);
    const nextDraft = { ...nextDraftWithoutAggregate, current_score: aggregate.total, pillar_scores: aggregate.pillars };
    const { error: userError } = await supabase.from("users").update({ onboarding_draft: nextDraft, current_score: aggregate.total, pillar_scores: aggregate.pillars }).eq("id", userId);
    setSaving(false);
    if (logError || userError) { setError((logError || userError)?.message || "Save failed."); return; }
    setDraft(nextDraft); setComputedTotal(Number(computedPoints.total || 0)); setMessage(`${msg} • ${Number(computedPoints.total || 0).toFixed(3)} pts today`); setTimeout(() => setMessage(""), 2200);
  }

  function addEntry(category: keyof EntryState, label: string, amount: number, note = "") { if (!amount || amount <= 0) return; const nextEntries = { ...entries, [category]: [...entries[category], { id: Date.now(), label, amount, note }] }; setEntries(nextEntries); save({ entries: nextEntries }, `${label} saved`); }
  function setGoal(slot: "goal1" | "goal2", value: string) { const nextGoals = { ...goals, [slot]: value }; setGoals(nextGoals); save({ goals: nextGoals }, "Goal saved"); }
  function markNextPrayer() { const prayer = nextPrayer(salah); const nextSalah = { ...salah, [prayer]: true }; setSalah(nextSalah); save({ salah: nextSalah }, `${prayer} saved`); setOpen("imaan"); }

  if (loading) return <main className={pageBg}><section className={`${cardClass} mx-auto max-w-xl`}>Loading today…</section><BottomNav /></main>;

  return <main className={pageBg}><div className="mx-auto max-w-5xl space-y-5"><section className="rounded-[2rem] bg-slate-950 p-6 text-white"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold text-emerald-300">Log Today</p><h1 className="mt-1 text-4xl font-black">{computedTotal.toFixed(3)} pts today</h1><p className="mt-2 text-slate-300">Small saves count. Log the next honest action.</p></div><div className="grid grid-cols-3 gap-2 text-center"><HeroStat label="Body" value={`${bodyProgress}%`} /><HeroStat label="Faith" value={`${faithProgress}%`} /><HeroStat label="Sabr" value={`${disciplineProgress}%`} /></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><QuickAction label="+1 cup water" primary onClick={() => addEntry("water", "+1 cup water", 1)} /><QuickAction label="+1k steps" onClick={() => addEntry("steps", "+1k steps", 1000)} /><QuickAction label="+10 min exercise" onClick={() => addEntry("exercise", "+10 min movement", 10)} /><QuickAction label={`Mark ${nextPrayer(salah)}`} onClick={markNextPrayer} /></div></section>{saving && <p className="rounded-xl bg-slate-50 p-3 text-sm font-bold text-slate-700">Saving…</p>}{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</p>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}
    <Accordion id="quwwah" open={open} setOpen={setOpen} title="QUWWAH — Body" progress={bodyProgress} summary={`${t.calories}/${targets.calories} cal • ${t.water}/${targets.water} cups • ${t.steps}/${targets.steps.toLocaleString()} steps`}><div className="grid gap-4 md:grid-cols-2"><EntryBox title="Calories" current={t.calories} target={targets.calories} unit="cal" labels={["Breakfast", "Lunch", "Dinner", "Snack"]} helper="Meals add up toward your daily calorie target." onSave={(label: string, amount: number, note: string) => addEntry("calories", label, amount, note)} /><EntryBox title="Water" current={t.water} target={targets.water} unit="cups" labels={["Cup", "Bottle", "Before meal"]} helper="One quick cup can move your Quwwah today." onSave={(label: string, amount: number, note: string) => addEntry("water", label, amount, note)} /><EntryBox title="Steps" current={t.steps} target={targets.steps} unit="steps" labels={["Morning", "Afternoon", "Walk"]} helper="Short walks count. Log what you actually did." onSave={(label: string, amount: number, note: string) => addEntry("steps", label, amount, note)} /><EntryBox title="Exercise" current={t.exercise} target={targets.exercise} unit="min" labels={[todayWorkout(draft), "Walking", "Gym", "Boxing"]} helper={`Today's plan: ${todayWorkout(draft)}`} onSave={(label: string, amount: number, note: string) => addEntry("exercise", label, amount, note)} /><label className="block rounded-2xl bg-slate-50 p-4"><span className="text-sm font-bold text-slate-700">Weight today</span><input className={inputClass} type="number" value={weight} onChange={(e) => setWeight(e.target.value)} onBlur={() => save({ weight }, "Weight saved")} placeholder="lbs" /></label><div className="grid gap-2 rounded-2xl bg-slate-50 p-4 md:grid-cols-2"><label><span className="text-sm font-bold text-slate-700">Bedtime target: {draft.bedtime || "9:00 PM"}</span><input className={inputClass} type="time" value={sleep.bedtime} onChange={(e) => setSleep({ ...sleep, bedtime: e.target.value })} onBlur={() => save({ sleep }, "Bedtime saved")} /></label><label><span className="text-sm font-bold text-slate-700">Wake target: {draft.wakeTime || "before Fajr"}</span><input className={inputClass} type="time" value={sleep.wake} onChange={(e) => setSleep({ ...sleep, wake: e.target.value })} onBlur={() => save({ sleep }, "Wake saved")} /></label></div></div></Accordion>
    <Accordion id="imaan" open={open} setOpen={setOpen} title="IMAAN — Faith" progress={faithProgress} summary={`${PRAYERS.filter((p) => (salah as any)[p]).length}/5 salah • ${t.quranMemorized}/${targets.memorize} new • ${t.quranReviewed}/${targets.review} review`}><div className="grid gap-4 md:grid-cols-2"><EntryBox title="Qur'an memorized" current={t.quranMemorized} target={targets.memorize} unit={draft.measurementUnit || "units"} labels={["After Fajr", "After Maghrib", "Before sleep"]} helper="New hifdh from your onboarding plan." onSave={(label: string, amount: number, note: string) => addEntry("quranMemorized", label, amount, note)} /><EntryBox title="Qur'an reviewed" current={t.quranReviewed} target={targets.review} unit={draft.measurementUnit || "units"} labels={[`Murajaa cycle ${draft.murajaaCycleDays || 10}d`, "Old review", "New review"]} helper={`Review target: ${targets.review} ${draft.measurementUnit || "units"} today.`} onSave={(label: string, amount: number, note: string) => addEntry("quranReviewed", label, amount, note)} /><div className="md:col-span-2 grid gap-2 md:grid-cols-5">{PRAYERS.map((p) => <label key={p} className={`rounded-xl p-3 text-sm font-bold ${((salah as any)[p]) ? "bg-emerald-100 text-emerald-900" : "bg-slate-50"}`}><input className="mr-2" type="checkbox" checked={(salah as any)[p]} onChange={(e) => { const nextSalah = { ...salah, [p]: e.target.checked }; setSalah(nextSalah); save({ salah: nextSalah }, `${p} saved`); }} />{p}</label>)}</div></div></Accordion>
    <Accordion id="sabr" open={open} setOpen={setOpen} title="SABR — Discipline" progress={disciplineProgress} summary={`$${t.money}/${targets.spending} • ${t.screen}/${targets.screen}h screen`}><div className="grid gap-4 md:grid-cols-2"><EntryBox title="Money spent" current={t.money} target={targets.spending} unit="$" labels={["Food", "Gas", "School", "Other"]} helper="Track honestly. Awareness is part of discipline." onSave={(label: string, amount: number, note: string) => addEntry("money", label, amount, note)} /><EntryBox title="Screen time" current={t.screen} target={targets.screen} unit="hours" labels={["Social", "YouTube", "Reels", "TV"]} helper="Screen time is a limit, not a goal. Lower is better." onSave={(label: string, amount: number, note: string) => addEntry("screen", label, amount, note)} /></div></Accordion>
    <Accordion id="niyyah" open={open} setOpen={setOpen} title="NIYYAH — Mission" progress={goals.goal1 || goals.goal2 ? 50 : 0} summary={`${draft.goal1 || "Goal 1"}: ${goals.goal1 || "not logged"} • ${draft.goal2 || "Goal 2"}: ${goals.goal2 || "not logged"}`}><div className="grid gap-4 md:grid-cols-2"><GoalBox title={draft.goal1 || "Personal Goal 1"} task={draft.goal1Task || draft.personalGoal1 || "Your first daily task"} value={goals.goal1} onChange={(v: string) => setGoal("goal1", v)} /><GoalBox title={draft.goal2 || "Personal Goal 2"} task={draft.goal2Task || draft.personalGoal2 || "Your second daily task"} value={goals.goal2} onChange={(v: string) => setGoal("goal2", v)} /></div></Accordion>
    <Accordion id="adab" open={open} setOpen={setOpen} title="ADAB — Character" progress={reflection.mood ? 60 : 0} summary={reflection.mood ? `Mood ${reflection.mood}/5 • reflection saved` : "Reflect before bed"}><div className="space-y-4"><div><p className="mb-2 text-sm font-bold text-slate-700">Mood check</p><div className="flex flex-wrap gap-2">{["1", "2", "3", "4", "5"].map((v) => <button key={v} onClick={() => { const next = { ...reflection, mood: v }; setReflection(next); save({ reflection: next }, "Mood saved"); }} className={`rounded-2xl px-5 py-3 text-lg font-black ${reflection.mood === v ? "bg-emerald-500 text-white" : "bg-slate-100 text-slate-700"}`}>{v}</button>)}</div></div><textarea className={inputClass} rows={3} placeholder="What went well?" value={reflection.wentWell} onChange={(e) => setReflection({ ...reflection, wentWell: e.target.value })} onBlur={() => save({ reflection }, "Reflection saved")} /><textarea className={inputClass} rows={3} placeholder="What slipped?" value={reflection.slipped} onChange={(e) => setReflection({ ...reflection, slipped: e.target.value })} onBlur={() => save({ reflection }, "Reflection saved")} /></div></Accordion>
    <div className="flex justify-center"><button onClick={() => save(undefined, "Today finalized")} className="rounded-full bg-emerald-600 px-6 py-3 font-black text-white shadow-xl">Finalize today</button></div></div><BottomNav /></main>;
}

function HeroStat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/10 px-4 py-3"><p className="text-xs font-bold text-slate-300">{label}</p><p className="text-lg font-black text-white">{value}</p></div>; }
function QuickAction({ label, onClick, primary = false }: { label: string; onClick: () => void; primary?: boolean }) { return <button onClick={onClick} className={`rounded-2xl px-4 py-3 text-sm font-black transition hover:-translate-y-0.5 ${primary ? "bg-emerald-400 text-slate-950" : "bg-white/10 text-white hover:bg-white/15"}`}>{label}</button>; }
function ProgressBar({ value }: { value: number }) { return <div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500 transition-all" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }
function Accordion({ id, open, setOpen, title, summary, progress = 0, children }: AccordionProps) { const isOpen = open === id; return <section className={cardClass}><button onClick={() => setOpen(isOpen ? "" : id)} className="flex w-full items-start justify-between gap-4 text-left"><div className="flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-black text-slate-950">{title}</h2><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">{progress}%</span></div><p className="mt-1 text-sm font-bold text-slate-500">{summary}</p><ProgressBar value={progress} /></div><span className="text-2xl font-black text-emerald-700">{isOpen ? "⌄" : "›"}</span></button>{isOpen && <div className="mt-5">{children}</div>}</section>; }
function quickAmounts(unit: string, target: number) { if (unit === "cups") return [1, 2, 3]; if (unit === "steps") return [1000, 2500, 5000]; if (unit === "cal") return [200, 500, 800]; if (unit === "min") return [10, 30, 45]; if (unit === "$") return [5, 10, 20]; if (unit === "hours") return [0.25, 0.5, 1]; return [1, Math.max(2, Math.round(target / 2)), Math.max(3, Math.round(target))]; }
function EntryBox({ title, current, target, unit, labels, onSave, helper }: EntryBoxProps) { const [label, setLabel] = useState(labels[0]); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const numericAmount = Number(amount); return <div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{title}</h3>{helper && <p className="mt-1 text-xs font-semibold text-slate-500">{helper}</p>}</div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-emerald-700">{current} / {target} {unit}</span></div><ProgressBar value={pct(current, target)} /><div className="mt-3 flex flex-wrap gap-2">{quickAmounts(unit, target).map((value) => <button type="button" key={value} onClick={() => setAmount(String(value))} className={`rounded-full px-3 py-1 text-xs font-black ${Number(amount) === value ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`}>+{value}</button>)}</div><div className="mt-3 grid gap-2 md:grid-cols-2"><select className={inputClass} value={label} onChange={(e) => setLabel(e.target.value)}>{labels.map((x: string) => <option key={x}>{x}</option>)}</select><input className={inputClass} type="number" value={amount} placeholder={`Add ${unit}`} onChange={(e) => setAmount(e.target.value)} /></div><input className={`${inputClass} mt-2`} placeholder="Optional note" value={note} onChange={(e) => setNote(e.target.value)} /><button disabled={!numericAmount || numericAmount <= 0} onClick={() => { onSave(label, Number(amount), note); setAmount(""); setNote(""); }} className="mt-3 rounded-full bg-emerald-600 px-4 py-2 text-sm font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300">Save entry</button></div>; }
function GoalBox({ title, task, value, onChange }: GoalBoxProps) { return <div className="rounded-2xl bg-slate-50 p-4"><h3 className="text-xl font-black">{title}</h3><p className="mt-1 text-sm font-bold text-slate-600">{task}</p><div className="mt-4 flex flex-wrap gap-2">{["done", "partial", "missed"].map((v) => <button key={v} onClick={() => onChange(v)} className={`rounded-full px-4 py-2 text-sm font-black ${value === v ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`}>{v}</button>)}</div></div>; }
