import type { LearningItem } from "./content-library";

const compactStories = [
  ["Abu Bakr رضي الله عنه Believes Immediately", "Abu Bakr رضي الله عنه knew the Prophet ﷺ as truthful and trustworthy, so when the message came, he accepted Islam without delay and supported the da'wah with his life, wealth, and reputation.", "Truthfulness makes the heart ready to accept guidance.", "سيرة ابن هشام، الطبقات الكبرى، سير أعلام النبلاء، الإصابة"],
  ["Abu Bakr رضي الله عنه Frees Bilal رضي الله عنه", "Abu Bakr رضي الله عنه used his wealth to support Bilal رضي الله عنه and help him gain freedom. Bilal later became the mu'adhdhin of the Prophet ﷺ.", "Use your blessings to support and protect others.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، الإصابة"],
  ["Abu Bakr رضي الله عنه in the Cave", "During the Hijrah, Abu Bakr رضي الله عنه worried when Quraysh came close to the cave. The Prophet ﷺ reminded him that Allah was with them.", "Take the means, then trust Allah completely.", "صحيح البخاري، صحيح مسلم، سيرة ابن هشام"],
  ["Abu Bakr رضي الله عنه Gives All His Wealth", "Before Tabuk, Abu Bakr رضي الله عنه gave everything he had for the sake of Allah. When asked what he left for his family, he replied with the meaning: Allah and His Messenger.", "True generosity appears when the cause of Allah needs you.", "سنن أبي داود، جامع الترمذي، سير أعلام النبلاء"],
  ["Abu Bakr رضي الله عنه After the Prophet ﷺ Passed Away", "When the companions were shaken by the passing of the Prophet ﷺ, Abu Bakr رضي الله عنه reminded them that Allah is Ever-Living and recited Qur'an to steady the ummah.", "Real leadership is firmness during grief.", "صحيح البخاري، البداية والنهاية، سير أعلام النبلاء"],
  ["Abu Bakr رضي الله عنه and Zakah", "After the Prophet ﷺ passed away, Abu Bakr رضي الله عنه stood firm when some people refused zakah. He protected a pillar of Islam at a fragile time.", "Mercy and firmness both have their place.", "صحيح البخاري، البداية والنهاية، تاريخ الطبري"],
  ["Umar رضي الله عنه Accepts Islam", "Umar رضي الله عنه heard verses from Surah Taha and Allah opened his heart. He went from opposition to becoming one of Islam's strongest supporters.", "Never assume someone is beyond Allah's guidance.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة"],
  ["Umar رضي الله عنه and Public Courage", "Reports describe Umar رضي الله عنه as courageous in migration, ready to stand openly for faith when many had to leave quietly.", "Courage should serve truth and strengthen others.", "أسد الغابة، سير أعلام النبلاء، الإصابة"],
  ["Umar رضي الله عنه Carries Food at Night", "As khalifah, Umar رضي الله عنه checked on people at night. When he found a family in need, he carried food himself and served them.", "Leadership means carrying people's burdens.", "الطبقات الكبرى، مناقب عمر، البداية والنهاية"],
  ["Umar رضي الله عنه Accepts Correction", "Umar رضي الله عنه was strong but humble. When reminded of Allah or corrected with truth, he returned to what was right.", "The best leaders are strong enough to be corrected.", "سير أعلام النبلاء، مناقب عمر، البداية والنهاية"],
  ["Uthman رضي الله عنه Buys the Well of Rumah", "Uthman رضي الله عنه bought the Well of Rumah and made its water available for the Muslims, turning wealth into ongoing charity.", "The best investment is reward that continues after death.", "جامع الترمذي، سنن النسائي، سير أعلام النبلاء"],
  ["Uthman رضي الله عنه Prepares Tabuk", "During the difficult expedition of Tabuk, Uthman رضي الله عنه gave generously to equip the Muslims and support the mission.", "Wealth is beautiful when it serves Allah.", "جامع الترمذي، مسند أحمد، البداية والنهاية"],
  ["Uthman رضي الله عنه and Modesty", "Uthman رضي الله عنه was known for deep modesty. The Prophet ﷺ praised this noble quality, showing that modesty is strength with dignity.", "Modesty is spiritual nobility, not weakness.", "صحيح مسلم، صحيح البخاري، سير أعلام النبلاء"],
  ["Uthman رضي الله عنه and Preserving the Qur'an", "During his khilafah, Uthman رضي الله عنه helped unite the ummah around preserved copies of the Qur'an to prevent confusion and division.", "Some service benefits generations you will never meet.", "صحيح البخاري، البداية والنهاية، سير أعلام النبلاء"],
  ["Ali رضي الله عنه Sleeps in the Prophet's Bed", "On the night of the Hijrah, Ali رضي الله عنه helped protect the plan and return people's trusts. He showed courage, loyalty, and sincerity while still young.", "Young people can be heroes with courage and sincerity.", "سيرة ابن هشام، الطبقات الكبرى، البداية والنهاية"],
  ["Ali رضي الله عنه and the Banner at Khaybar", "At Khaybar, the Prophet ﷺ said he would give the banner to a man who loved Allah and His Messenger ﷺ, and whom Allah and His Messenger ﷺ loved. He called Ali رضي الله عنه, prayed for him, and gave him the banner. Ali went forward with courage and faith.", "Real strength is faith, sincerity, and love for Allah and His Messenger ﷺ.", "صحيح البخاري، صحيح مسلم، البداية والنهاية، سير أعلام النبلاء"],
  ["Ali رضي الله عنه and His Simple Life", "Ali رضي الله عنه was from the family of the Prophet ﷺ, an early Muslim, scholar, brave companion, and later khalifah. Yet he lived simply with humility, patience, and focus on the akhirah.", "You can be important in people's eyes while living humbly before Allah.", "الطبقات الكبرى، سير أعلام النبلاء، حلية الأولياء، البداية والنهاية"],
  ["Al-Zubayr رضي الله عنه: The First Sword for Islam", "Al-Zubayr ibn al-Awwam رضي الله عنه accepted Islam while young. Reports mention that when he heard a rumor that the Prophet ﷺ had been harmed, he came out ready to defend him, showing loyalty and love.", "Love is proven by loyalty, courage, and readiness to protect what is sacred.", "أسد الغابة، الإصابة، سير أعلام النبلاء، الطبقات الكبرى"],
  ["Talhah رضي الله عنه Defends the Prophet ﷺ at Uhud", "At Uhud, Talhah ibn Ubaydillah رضي الله عنه stood firm in a dangerous moment and protected the Prophet ﷺ with incredible loyalty and courage. He became remembered among the heroes of Uhud.", "True love for the Prophet ﷺ is shown through sacrifice and loyalty.", "جامع الترمذي، سيرة ابن هشام، الطبقات الكبرى، سير أعلام النبلاء"],
  ["Abd al-Rahman ibn Awf رضي الله عنه Starts Over", "When Abd al-Rahman ibn Awf رضي الله عنه migrated to Madinah, his Ansari brother offered to share wealth with him. Abd al-Rahman thanked him and asked to be shown the marketplace. He rebuilt through halal work and Allah blessed him.", "A believer can rebuild with tawakkul, effort, and halal work.", "صحيح البخاري، الطبقات الكبرى، سير أعلام النبلاء، الإصابة"],
  ["Abd al-Rahman ibn Awf رضي الله عنه and Generosity", "Abd al-Rahman ibn Awf رضي الله عنه became wealthy, but his wealth flowed toward good. He supported the poor, the Muslims, and the families of the Prophet ﷺ.", "Build success, but make sure your success serves Allah and helps people.", "الطبقات الكبرى، سير أعلام النبلاء، أسد الغابة، الإصابة"],
  ["Sa'd ibn Abi Waqqas رضي الله عنه and His Mother", "Sa'd رضي الله عنه accepted Islam while young. His mother pressured him to leave Islam, but he stayed firm while still maintaining respect. His story reflects the Qur'anic balance of kindness to parents and obedience to Allah above all.", "Respect your parents deeply, but never obey anyone in disobedience to Allah.", "صحيح مسلم، تفسير الطبري، تفسير ابن كثير، الطبقات الكبرى"],
  ["Sa'd ibn Abi Waqqas رضي الله عنه and the First Arrow", "Sa'd رضي الله عنه is remembered in reports as the first to shoot an arrow in defense of Islam. He used the strength Allah gave him to serve truth and protect the Muslims.", "Whatever strength Allah gave you, use it for truth and service.", "الطبقات الكبرى، أسد الغابة، الإصابة، سير أعلام النبلاء"],
  ["Sa'd ibn Abi Waqqas رضي الله عنه at al-Qadisiyyah", "Years after accepting Islam, Sa'd رضي الله عنه became a leader at al-Qadisiyyah. Despite difficulty and illness, he continued directing the Muslims with patience, discipline, and reliance on Allah.", "Early patience prepares people for future leadership.", "تاريخ الطبري، البداية والنهاية، سير أعلام النبلاء، الإصابة"],
  ["Abu Ubaydah رضي الله عنه: The Trustworthy One", "Abu Ubaydah ibn al-Jarrah رضي الله عنه was called the trustworthy one of this ummah. When trustworthy leadership was needed, the Prophet ﷺ chose him.", "Be the person people can trust with responsibility, secrets, money, and truth.", "صحيح البخاري، صحيح مسلم، سير أعلام النبلاء، الإصابة"],
  ["Abu Ubaydah رضي الله عنه and Leadership Without Ego", "Abu Ubaydah رضي الله عنه led with humility during major campaigns. Authority did not make him arrogant; he remained focused on service, justice, and responsibility before Allah.", "True leadership is service without ego.", "البداية والنهاية، تاريخ الطبري، سير أعلام النبلاء، أسد الغابة"],
  ["Bilal رضي الله عنه Says Ahad, Ahad", "Bilal رضي الله عنه faced intense pressure in Makkah because of his belief in Allah alone. He stayed firm and repeated: Ahad, Ahad — One, One. His words became a symbol of tawheed.", "A heart attached to Allah cannot be defeated by people.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، الإصابة، سير أعلام النبلاء"],
  ["Bilal رضي الله عنه Becomes the Mu'adhdhin", "After years of hardship in Makkah, Bilal رضي الله عنه was honored in Madinah as the caller to prayer for the Prophet ﷺ. Allah raised the same voice that had stayed firm upon tawheed.", "If you stay firm for Allah, He can raise you in ways people never expected.", "صحيح البخاري، صحيح مسلم، الطبقات الكبرى، سير أعلام النبلاء"],
  ["Bilal رضي الله عنه and His Footsteps in Jannah", "The Prophet ﷺ told Bilal رضي الله عنه that he had heard his footsteps in Paradise. Bilal mentioned his habit of praying after wudu whenever Allah allowed him to pray.", "Small deeds done consistently can become huge with Allah.", "صحيح البخاري، صحيح مسلم، رياض الصالحين"],
  ["Khabbab ibn al-Aratt رضي الله عنه and Patience", "Khabbab رضي الله عنه was among the early Muslims who faced severe hardship in Makkah. When he asked the Prophet ﷺ for relief, the Prophet ﷺ reminded him that victory would come, but patience was needed.", "Hardship does not mean Allah abandoned you; sometimes it means Allah is building you.", "صحيح البخاري، سيرة ابن هشام، الطبقات الكبرى، سير أعلام النبلاء"],
  ["Khabbab رضي الله عنه Asks for Victory", "Khabbab رضي الله عنه came to the Prophet ﷺ during the difficult years in Makkah and asked for dua and relief. The Prophet ﷺ reminded him that believers before them were tested severely, then gave hope that Allah would complete this religion and bring safety.", "When hardship feels long, Allah's help may be delayed, but it is never forgotten.", "صحيح البخاري، سيرة ابن هشام، الطبقات الكبرى، سير أعلام النبلاء"],
  ["Ammar ibn Yasir رضي الله عنه and the Family of Patience", "Ammar رضي الله عنه came from a family that suffered greatly for Islam. The Prophet ﷺ comforted the family of Yasir with the promise of Paradise, showing that their patience was honored by Allah.", "A weak-looking family in people's eyes can be among the greatest with Allah.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، الإصابة، سير أعلام النبلاء"],
  ["Sumayyah bint Khayyat رضي الله عنها: The First Martyr", "Sumayyah رضي الله عنها was among the earliest believers and remained firm when pressured to leave Islam. She became known as the first martyr in Islam and a timeless example of courage.", "One sincere believer can become greater than a whole system of oppression.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، الإصابة، الاستيعاب"],
  ["Yasir رضي الله عنه and the Price of Faith", "Yasir رضي الله عنه was part of the family of patience in Makkah. He remained firm with his family through hardship and became a symbol of a household that chose Allah over comfort and safety.", "A believing family can turn suffering into a path to Jannah.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، الإصابة"],
  ["Mus'ab ibn Umayr رضي الله عنه Leaves Luxury", "Mus'ab رضي الله عنه was a wealthy and elegant young man in Makkah, but when Islam entered his heart, he chose Allah and His Messenger ﷺ over luxury, image, and social pressure.", "If your heart finds the truth, do not sell it for comfort.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، سير أعلام النبلاء"],
  ["Mus'ab ibn Umayr رضي الله عنه Teaches Islam in Madinah", "Before the Hijrah, the Prophet ﷺ sent Mus'ab رضي الله عنه to Madinah to teach Qur'an and Islam. Through his wisdom, manners, and da'wah, the city became ready to receive the Prophet ﷺ.", "A sincere young teacher can help prepare an entire community for guidance.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، الإصابة"],
  ["Mus'ab ibn Umayr رضي الله عنه at Uhud", "At Uhud, Mus'ab رضي الله عنه carried the Muslim banner and stood firm until he was martyred. He had once lived in luxury, but left dunya for eternal honor.", "The one who gives up temporary beauty for Allah gains eternal honor.", "صحيح البخاري، سيرة ابن هشام، الطبقات الكبرى، سير أعلام النبلاء"],
  ["Ja'far ibn Abi Talib رضي الله عنه Speaks to the Najashi", "When Muslims migrated to Abyssinia, Ja'far رضي الله عنه spoke before the Najashi with wisdom and courage. He explained Islam beautifully and recited from Surah Maryam, and the Muslims were protected.", "Defending Islam requires knowledge, wisdom, manners, and courage.", "سيرة ابن هشام، مسند أحمد، دلائل النبوة، البداية والنهاية"],
  ["Ja'far ibn Abi Talib رضي الله عنه at Mu'tah", "At Mu'tah, Ja'far رضي الله عنه took the banner after Zayd رضي الله عنه. He fought with courage and was honored by Allah with a noble replacement in Paradise.", "What you lose for Allah is replaced by something better with Allah.", "صحيح البخاري، سيرة ابن هشام، البداية والنهاية، سير أعلام النبلاء"],
  ["Hamzah رضي الله عنه Defends the Prophet ﷺ", "Hamzah رضي الله عنه defended the Prophet ﷺ after hearing that Abu Jahl had insulted and harmed him. Soon after, Allah opened his heart to Islam and he became a strength for the Muslims.", "Sometimes defending someone from injustice becomes the doorway to guidance.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، الإصابة"],
  ["Hamzah رضي الله عنه at Badr", "At Badr, Hamzah رضي الله عنه fought with courage among the believers. His strength was no longer for pride or tribe; it became service to Allah.", "Physical strength becomes noble when it is guided by faith.", "سيرة ابن هشام، البداية والنهاية، الطبقات الكبرى، سير أعلام النبلاء"],
  ["Hamzah رضي الله عنه: The Lion of Allah at Uhud", "At Uhud, Hamzah رضي الله عنه was martyred after a life of courage, protection, and service. He was beloved to the Prophet ﷺ and honored as a martyr.", "A believer's death for Allah is not the end of honor; it begins eternal reward.", "صحيح البخاري، سيرة ابن هشام، الطبقات الكبرى، البداية والنهاية"],
  ["Abdullah ibn Mas'ud رضي الله عنه Recites Qur'an Publicly", "In Makkah, Abdullah ibn Mas'ud رضي الله عنه recited Qur'an aloud near the Ka'bah when Quraysh tried to silence it. Though not physically powerful, he showed a brave heart.", "Do not measure courage by body size; measure it by firmness upon truth.", "سيرة ابن هشام، الطبقات الكبرى، أسد الغابة، سير أعلام النبلاء"],
  ["Abdullah ibn Mas'ud رضي الله عنه and Knowledge of Qur'an", "Abdullah ibn Mas'ud رضي الله عنه became one of the greatest scholars of Qur'an. His dedication shows that Allah raises people through knowledge and closeness to His Book.", "The Qur'an raises people when they dedicate their lives to it.", "صحيح البخاري، صحيح مسلم، سير أعلام النبلاء، الإصابة"],
  ["Abu Hurayrah رضي الله عنه and Love of Hadith", "Abu Hurayrah رضي الله عنه accepted Islam later than many companions, but devoted himself to staying close to the Prophet ﷺ and memorizing hadith. Allah blessed his dedication with benefit for generations.", "You may start late, but sincerity and consistency can make your impact huge.", "صحيح البخاري، صحيح مسلم، سير أعلام النبلاء، الإصابة"],
] as const;

export const dailyStoryBank: LearningItem[] = compactStories.map(([title, story, lesson, reference], index) => ({
  id: `daily-story-${String(index + 1).padStart(3, "0")}`,
  type: "sahaba_story",
  title,
  shortText: story,
  fullText: `${story}\n\nLesson: ${lesson}`,
  reference,
  themes: ["Sahaba", "Story", "Daily"],
  readingTimeSeconds: 75,
}));

export function getDailyStory(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((date.getTime() - start.getTime()) / 86400000);
  return dailyStoryBank[dayOfYear % dailyStoryBank.length];
}
