import type { LearningItem } from "./content-library";

const ayahs: Array<[string, string]> = [
  ["وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ", "Seek help through patience and prayer."],
  ["إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", "Allah is with the patient."],
  ["لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", "Allah does not burden a soul beyond what it can handle."],
  ["فَإِنَّ مَعَ الْعُسْرِ يُسْرًا", "With hardship comes ease."],
  ["إِنَّ مَعَ الْعُسْرِ يُسْرًا", "Truly, with hardship comes ease."],
  ["أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ", "Hearts find peace in the remembrance of Allah."],
  ["وَمَنْ يَتَّقِ اللَّهَ يَجْعَلْ لَهُ مَخْرَجًا", "Whoever has taqwa, Allah will make a way out."],
  ["وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ", "Allah provides from places you never expected."],
  ["وَمَنْ يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ", "Whoever trusts Allah, Allah is enough for him."],
  ["لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ", "Do not despair of Allah’s mercy."],
  ["إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا", "Allah forgives all sins."],
  ["ادْعُونِي أَسْتَجِبْ لَكُمْ", "Call upon Me; I will respond to you."],
  ["وَقُلْ رَبِّ زِدْنِي عِلْمًا", "Say: My Lord, increase me in knowledge."],
  ["إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِنَ الْمُحْسِنِينَ", "Allah’s mercy is near to those who do good."],
  ["وَاصْبِرْ فَإِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ", "Be patient; Allah does not waste the reward of good-doers."],
  ["إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنْفُسِهِمْ", "Allah does not change a people until they change themselves."],
  ["وَأَنْ لَيْسَ لِلْإِنْسَانِ إِلَّا مَا سَعَىٰ", "A person will only have what they strive for."],
  ["فَاذْكُرُونِي أَذْكُرْكُمْ", "Remember Me, and I will remember you."],
  ["لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُمْ", "If you are grateful, I will increase you."],
  ["وَلَا تَهِنُوا وَلَا تَحْزَنُوا", "Do not weaken and do not grieve."],
  ["وَأَنْتُمُ الْأَعْلَوْنَ إِنْ كُنْتُمْ مُؤْمِنِينَ", "You will be superior if you are believers."],
  ["وَاللَّهُ يُحِبُّ الصَّابِرِينَ", "Allah loves the patient."],
  ["إِنْ يَنْصُرْكُمُ اللَّهُ فَلَا غَالِبَ لَكُمْ", "If Allah helps you, none can overcome you."],
  ["حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", "Allah is sufficient for us and the best disposer of affairs."],
  ["كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ", "Every soul will taste death."],
  ["فَمَنْ زُحْزِحَ عَنِ النَّارِ وَأُدْخِلَ الْجَنَّةَ فَقَدْ فَازَ", "True success is being saved from the Fire and entering Paradise."],
  ["وَاللَّهُ لَا يُحِبُّ الظَّالِمِينَ", "Allah does not love oppressors."],
  ["إِنَّ اللَّهَ لَا يَظْلِمُ مِثْقَالَ ذَرَّةٍ", "Allah does not wrong anyone even by an atom’s weight."],
  ["وَمَنْ يَعْمَلْ سُوءًا أَوْ يَظْلِمْ نَفْسَهُ ثُمَّ يَسْتَغْفِرِ اللَّهَ", "Whoever sins then seeks forgiveness will find Allah Forgiving."],
  ["كُونُوا قَوَّامِينَ بِالْقِسْطِ", "Stand firmly for justice."],
  ["اعْدِلُوا هُوَ أَقْرَبُ لِلتَّقْوَىٰ", "Be just; that is closer to taqwa."],
  ["وَتَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَىٰ", "Cooperate in righteousness and taqwa."],
  ["وَلَا تَعَاوَنُوا عَلَى الْإِثْمِ وَالْعُدْوَانِ", "Do not cooperate in sin and aggression."],
  ["إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ", "My prayer, worship, life, and death are for Allah."],
  ["وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ", "My mercy encompasses all things."],
  ["فَاصْبِرْ صَبْرًا جَمِيلًا", "Be patient with beautiful patience."],
  ["وَلَا تَنَازَعُوا فَتَفْشَلُوا", "Do not dispute, or you will lose strength."],
  ["إِنَّ اللَّهَ مَعَنَا", "Allah is with us."],
  ["قُلْ لَنْ يُصِيبَنَا إِلَّا مَا كَتَبَ اللَّهُ لَنَا", "Nothing will happen to us except what Allah has written for us."],
  ["أَلَا إِنَّ أَوْلِيَاءَ اللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ", "The friends of Allah have no fear and no grief."],
  ["وَمَا تَوْفِيقِي إِلَّا بِاللَّهِ", "My success is only through Allah."],
  ["إِنَّهُ لَا يَيْأَسُ مِنْ رَوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ", "None despairs of Allah’s relief except those who reject faith."],
  ["إِنَّهُ مَنْ يَتَّقِ وَيَصْبِرْ فَإِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ", "Whoever has taqwa and patience, Allah does not waste their reward."],
  ["إِنَّ رَبِّي لَطِيفٌ لِمَا يَشَاءُ", "My Lord is subtle and gentle in what He wills."],
  ["وَفَوْقَ كُلِّ ذِي عِلْمٍ عَلِيمٌ", "Above every person of knowledge is One more knowing."],
  ["وَقُلِ اعْمَلُوا فَسَيَرَى اللَّهُ عَمَلَكُمْ", "Work, for Allah will see your deeds."],
  ["وَلَئِنْ صَبَرْتُمْ لَهُوَ خَيْرٌ لِلصَّابِرِينَ", "If you are patient, it is better for those who are patient."],
  ["مَنْ عَمِلَ صَالِحًا فَلِنَفْسِهِ", "Whoever does good, it is for their own soul."],
  ["مَنْ عَمِلَ صَالِحًا مِنْ ذَكَرٍ أَوْ أُنْثَىٰ وَهُوَ مُؤْمِنٌ", "Whoever does righteousness, male or female, while believing…"],
  ["فَلَنُحْيِيَنَّهُ حَيَاةً طَيِّبَةً", "We will give them a good life."],
  ["وَإِنْ تَعُدُّوا نِعْمَةَ اللَّهِ لَا تُحْصُوهَا", "If you tried to count Allah’s blessings, you could never count them."],
  ["إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ", "Allah commands justice and excellence."],
  ["وَاخْفِضْ لَهُمَا جَنَاحَ الذُّلِّ مِنَ الرَّحْمَةِ", "Be humble and merciful to your parents."],
  ["وَلَقَدْ كَرَّمْنَا بَنِي آدَمَ", "We have honored the children of Adam."],
  ["عَسَىٰ رَبُّكُمْ أَنْ يَرْحَمَكُمْ", "Perhaps your Lord will have mercy on you."],
  ["إِنَّهُمْ فِتْيَةٌ آمَنُوا بِرَبِّهِمْ", "They were youth who believed in their Lord."],
  ["وَزِدْنَاهُمْ هُدًى", "And We increased them in guidance."],
  ["وَاصْبِرْ نَفْسَكَ مَعَ الَّذِينَ يَدْعُونَ رَبَّهُمْ", "Keep yourself with those who call upon their Lord."],
  ["الْمَالُ وَالْبَنُونَ زِينَةُ الْحَيَاةِ الدُّنْيَا", "Wealth and children are the decoration of worldly life."],
  ["وَالْبَاقِيَاتُ الصَّالِحَاتُ خَيْرٌ", "Lasting righteous deeds are better."],
  ["وَلَمْ أَكُنْ بِدُعَائِكَ رَبِّ شَقِيًّا", "My Lord, I have never been disappointed in calling upon You."],
  ["سَيَجْعَلُ لَهُمُ الرَّحْمَٰنُ وُدًّا", "The Most Merciful will place love for the righteous."],
  ["إِنَّنِي مَعَكُمَا أَسْمَعُ وَأَرَىٰ", "I am with you both; I hear and I see."],
  ["وَعَجِلْتُ إِلَيْكَ رَبِّ لِتَرْضَىٰ", "I hurried to You, my Lord, so You may be pleased."],
  ["وَنَضَعُ الْمَوَازِينَ الْقِسْطَ", "We will set up the scales of justice."],
  ["فَاسْتَجَبْنَا لَهُ", "So We answered him."],
  ["إِنَّهُمْ كَانُوا يُسَارِعُونَ فِي الْخَيْرَاتِ", "They used to rush toward good deeds."],
  ["وَيَدْعُونَنَا رَغَبًا وَرَهَبًا", "They called upon Us with hope and fear."],
  ["قَدْ أَفْلَحَ الْمُؤْمِنُونَ", "Successful indeed are the believers."],
  ["الَّذِينَ هُمْ فِي صَلَاتِهِمْ خَاشِعُونَ", "Those who are humble in their prayer."],
  ["فَتَعَالَى اللَّهُ الْمَلِكُ الْحَقُّ", "Exalted is Allah, the True King."],
  ["اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ", "Allah is the Light of the heavens and the earth."],
  ["وَعِبَادُ الرَّحْمَٰنِ الَّذِينَ يَمْشُونَ عَلَى الْأَرْضِ هَوْنًا", "The servants of the Most Merciful walk humbly on earth."],
  ["إِلَّا مَنْ تَابَ وَآمَنَ وَعَمِلَ عَمَلًا صَالِحًا", "Except those who repent, believe, and do righteous deeds."],
  ["فَأُولَٰئِكَ يُبَدِّلُ اللَّهُ سَيِّئَاتِهِمْ حَسَنَاتٍ", "Allah will replace their bad deeds with good deeds."],
  ["وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ", "When I am sick, He heals me."],
  ["أَنِ اشْكُرْ لِي وَلِوَالِدَيْكَ", "Be grateful to Me and to your parents."],
  ["يَا بُنَيَّ أَقِمِ الصَّلَاةَ", "My son, establish prayer."],
  ["وَأْمُرْ بِالْمَعْرُوفِ", "Command what is good."],
  ["وَانْهَ عَنِ الْمُنْكَرِ", "Forbid what is wrong."],
  ["وَاصْبِرْ عَلَىٰ مَا أَصَابَكَ", "Be patient with what happens to you."],
  ["وَلَا تُصَعِّرْ خَدَّكَ لِلنَّاسِ", "Do not turn your cheek away from people arrogantly."],
  ["وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا", "Do not walk on earth with arrogance."],
  ["إِنَّ اللَّهَ لَا يُحِبُّ كُلَّ مُخْتَالٍ فَخُورٍ", "Allah does not love the arrogant boaster."],
  ["وَتَوَكَّلْ عَلَى اللَّهِ", "Put your trust in Allah."],
  ["وَكَفَىٰ بِاللَّهِ وَكِيلًا", "Allah is enough as a guardian."],
  ["لَقَدْ كَانَ لَكُمْ فِي رَسُولِ اللَّهِ أُسْوَةٌ حَسَنَةٌ", "The Messenger of Allah is the best example for you."],
  ["اذْكُرُوا اللَّهَ ذِكْرًا كَثِيرًا", "Remember Allah often."],
  ["وَسَبِّحُوهُ بُكْرَةً وَأَصِيلًا", "Glorify Him morning and evening."],
  ["إِنَّ اللَّهَ وَمَلَائِكَتَهُ يُصَلُّونَ عَلَى النَّبِيِّ", "Allah and His angels send blessings upon the Prophet ﷺ."],
  ["هَلْ جَزَاءُ الْإِحْسَانِ إِلَّا الْإِحْسَانُ", "Is the reward of excellence anything but excellence?"],
  ["فَاذْكُرُوا اسْمَ اللَّهِ عَلَيْهَا", "Remember Allah’s name over it."],
  ["يَا أَيُّهَا الَّذِينَ آمَنُوا إِنْ تَنْصُرُوا اللَّهَ يَنْصُرْكُمْ", "If you support Allah’s cause, He will support you."],
  ["وَيُثَبِّتْ أَقْدَامَكُمْ", "And He will make your feet firm."],
  ["إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ", "The believers are brothers."],
  ["فَأَصْلِحُوا بَيْنَ أَخَوَيْكُمْ", "So make peace between your brothers."],
  ["إِنَّ أَكْرَمَكُمْ عِنْدَ اللَّهِ أَتْقَاكُمْ", "The most honored among you before Allah are those with the most taqwa."],
  ["وَهُوَ مَعَكُمْ أَيْنَ مَا كُنْتُمْ", "He is with you wherever you are."],
  ["سَابِقُوا إِلَىٰ مَغْفِرَةٍ مِنْ رَبِّكُمْ", "Race toward forgiveness from your Lord."],
  ["وَجَنَّةٍ عَرْضُهَا كَعَرْضِ السَّمَاءِ وَالْأَرْضِ", "And toward Paradise as wide as the heavens and the earth."],
];

export const extendedAyahBank: LearningItem[] = ayahs.map(([arabicText, shortText], index) => ({
  id: `verse-${String(index + 1).padStart(3, "0")}`,
  type: "verse",
  title: `Motivational Ayah ${index + 1}`,
  arabicText,
  shortText,
  reference: "Qur'an reference — verify before publishing",
  themes: ["Motivation", "Qur'an", index % 3 === 0 ? "Hope" : index % 3 === 1 ? "Patience" : "Discipline"],
  readingTimeSeconds: 30,
}));
