import type { DuaItem } from "./dua-bank";

const duas: Array<[string, string]> = [
  ["رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ", "Our Lord, accept from us. You are the All-Hearing, All-Knowing."],
  ["رَبَّنَا وَاجْعَلْنَا مُسْلِمَيْنِ لَكَ", "Our Lord, make us submitted to You."],
  ["رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", "Our Lord, give us good in this world and good in the Hereafter, and protect us from the Fire."],
  ["رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانْصُرْنَا", "Our Lord, pour patience upon us, make our feet firm, and grant us victory."],
  ["رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِينَا أَوْ أَخْطَأْنَا", "Our Lord, do not hold us accountable if we forget or make mistakes."],
  ["رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا", "Our Lord, do not let our hearts deviate after You guided us."],
  ["رَبَّنَا هَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً", "Our Lord, grant us mercy from Yourself."],
  ["رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا", "Our Lord, forgive us our sins."],
  ["رَبَّنَا ظَلَمْنَا أَنْفُسَنَا", "Our Lord, we have wronged ourselves."],
  ["رَبِّ زِدْنِي عِلْمًا", "My Lord, increase me in knowledge."],
  ["رَبِّ اشْرَحْ لِي صَدْرِي", "My Lord, expand my chest."],
  ["وَيَسِّرْ لِي أَمْرِي", "And make my task easy for me."],
  ["رَبِّ اغْفِرْ وَارْحَمْ", "My Lord, forgive and have mercy."],
  ["رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ", "My Lord, I am truly in need of whatever good You send down to me."],
  ["رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ", "My Lord, grant me righteous offspring/company."],
  ["رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ", "My Lord, make me one who establishes prayer."],
  ["رَبَّنَا وَتَقَبَّلْ دُعَاءِ", "Our Lord, accept my dua."],
  ["رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ", "Our Lord, forgive me and my parents."],
  ["رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", "My Lord, have mercy on my parents as they raised me when I was young."],
  ["رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ", "Our Lord, grant us from our spouses and children comfort to our eyes."],
  ["وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا", "And make us leaders for the righteous."],
  ["رَبَّنَا أَتْمِمْ لَنَا نُورَنَا", "Our Lord, complete our light for us."],
  ["رَبَّنَا وَاغْفِرْ لَنَا", "Our Lord, forgive us."],
  ["رَبَّنَا عَلَيْكَ تَوَكَّلْنَا", "Our Lord, upon You we rely."],
  ["وَإِلَيْكَ أَنَبْنَا", "And to You we return in repentance."],
  ["وَإِلَيْكَ الْمَصِيرُ", "And to You is the final return."],
  ["رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِلَّذِينَ كَفَرُوا", "Our Lord, do not make us a trial for those who disbelieve."],
  ["رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا", "Our Lord, forgive us and our brothers and sisters."],
  ["وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا", "Do not place hatred in our hearts."],
  ["رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ", "My Lord, inspire me to be grateful for Your blessing."],
  ["وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ", "And help me do righteous deeds that please You."],
  ["وَأَدْخِلْنِي بِرَحْمَتِكَ فِي عِبَادِكَ الصَّالِحِينَ", "Admit me by Your mercy among Your righteous servants."],
  ["لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ", "There is no god but You. Glory be to You. I was among the wrongdoers."],
  ["حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", "Allah is sufficient for us, and He is the best disposer of affairs."],
  ["نِعْمَ الْمَوْلَىٰ وَنِعْمَ النَّصِيرُ", "He is the best Protector and the best Helper."],
  ["اللَّهُمَّ اغْفِرْ لِي", "O Allah, forgive me."],
  ["اللَّهُمَّ ارْحَمْنِي", "O Allah, have mercy on me."],
  ["اللَّهُمَّ اهْدِنِي", "O Allah, guide me."],
  ["اللَّهُمَّ عَافِنِي", "O Allah, grant me well-being."],
  ["اللَّهُمَّ ارْزُقْنِي", "O Allah, provide for me."],
  ["اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَىٰ وَالتُّقَىٰ وَالْعَفَافَ وَالْغِنَىٰ", "O Allah, I ask You for guidance, taqwa, purity, and contentment."],
  ["اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا", "O Allah, I ask You for beneficial knowledge."],
  ["وَرِزْقًا طَيِّبًا", "And pure provision."],
  ["وَعَمَلًا مُتَقَبَّلًا", "And accepted deeds."],
  ["اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ", "O Allah, I seek refuge in You from anxiety and sadness."],
  ["وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ", "And I seek refuge in You from weakness and laziness."],
  ["وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ", "And I seek refuge in You from cowardice and stinginess."],
  ["وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ", "And I seek refuge in You from being overcome by debt and people."],
  ["اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي", "O Allah, You are Pardoning and love to pardon, so pardon me."],
  ["أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ", "I seek Allah’s forgiveness and repent to Him."],
  ["سُبْحَانَ اللَّهِ", "Glory be to Allah."],
  ["الْحَمْدُ لِلَّهِ", "All praise is due to Allah."],
  ["اللَّهُ أَكْبَرُ", "Allah is the Greatest."],
  ["لَا إِلَٰهَ إِلَّا اللَّهُ", "There is no god except Allah."],
  ["لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", "There is no power or strength except through Allah."],
  ["سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", "Glory and praise be to Allah."],
  ["سُبْحَانَ اللَّهِ الْعَظِيمِ", "Glory be to Allah, the Magnificent."],
  ["اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ", "O Allah, send blessings upon Muhammad ﷺ."],
  ["اللَّهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ", "O Allah, send blessings and barakah upon Muhammad ﷺ."],
  ["بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ", "In the name of Allah, I place my trust in Allah."],
  ["اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذَا الْيَوْمِ", "O Allah, I ask You for the good of this day."],
  ["وَأَعُوذُ بِكَ مِنْ شَرِّ هَذَا الْيَوْمِ", "And I seek refuge in You from the evil of this day."],
  ["اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا", "O Allah, by You we enter morning and evening."],
  ["وَبِكَ نَحْيَا وَبِكَ نَمُوتُ", "By You we live and by You we die."],
  ["اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ", "O Allah, You are my Lord; none has the right to be worshiped except You."],
  ["خَلَقْتَنِي وَأَنَا عَبْدُكَ", "You created me, and I am Your servant."],
  ["اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ", "O Allah, I seek refuge in You from knowledge that does not benefit."],
  ["وَمِنْ قَلْبٍ لَا يَخْشَعُ", "And from a heart that does not humble itself."],
  ["وَمِنْ نَفْسٍ لَا تَشْبَعُ", "And from a soul that is never satisfied."],
  ["وَمِنْ دَعْوَةٍ لَا يُسْتَجَابُ لَهَا", "And from a dua that is not answered."],
  ["اللَّهُمَّ أَحْسِنْ عَاقِبَتَنَا فِي الْأُمُورِ كُلِّهَا", "O Allah, make the end of all our affairs good."],
  ["وَأَجِرْنَا مِنْ خِزْيِ الدُّنْيَا وَعَذَابِ الْآخِرَةِ", "Protect us from disgrace in this world and punishment in the Hereafter."],
  ["اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ", "O Allah, I ask You for Paradise."],
  ["وَأَعُوذُ بِكَ مِنَ النَّارِ", "And I seek refuge in You from the Fire."],
  ["اللَّهُمَّ إِنِّي أَسْأَلُكَ حُبَّكَ", "O Allah, I ask You for Your love."],
  ["وَحُبَّ مَنْ يُحِبُّكَ", "And the love of those who love You."],
  ["وَحُبَّ عَمَلٍ يُقَرِّبُنِي إِلَىٰ حُبِّكَ", "And love of deeds that bring me closer to Your love."],
  ["اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ", "O Allah, make me among those who repent often."],
  ["وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ", "And make me among those who purify themselves."],
  ["اللَّهُمَّ اجْعَلْ خَيْرَ عُمْرِي آخِرَهُ", "O Allah, make the best of my life its ending."],
  ["وَخَيْرَ عَمَلِي خَوَاتِيمَهُ", "And make the best of my deeds the final ones."],
  ["وَخَيْرَ أَيَّامِي يَوْمَ أَلْقَاكَ", "And make the best of my days the day I meet You."],
  ["اللَّهُمَّ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ", "O Allah, keep my heart firm upon Your religion."],
  ["يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ", "O Turner of hearts, keep my heart firm upon Your religion."],
  ["اللَّهُمَّ أَصْلِحْ لِي دِينِي", "O Allah, correct my religion for me."],
  ["وَأَصْلِحْ لِي دُنْيَايَ", "And correct my worldly life for me."],
  ["وَأَصْلِحْ لِي آخِرَتِي", "And correct my Hereafter for me."],
  ["اللَّهُمَّ زَيِّنَّا بِزِينَةِ الْإِيمَانِ", "O Allah, beautify us with the beauty of faith."],
  ["وَاجْعَلْنَا هُدَاةً مُهْتَدِينَ", "And make us guided people who guide others."],
  ["اللَّهُمَّ إِنِّي أَسْأَلُكَ رِضَاكَ", "O Allah, I ask You for Your pleasure."],
  ["اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ سَخَطِكَ", "O Allah, I seek refuge in You from Your anger."],
  ["اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ", "O Allah, I ask You for well-being."],
  ["اللَّهُمَّ اشْفِنِي شِفَاءً لَا يُغَادِرُ سَقَمًا", "O Allah, heal me with a healing that leaves no illness."],
  ["اللَّهُمَّ بَارِكْ لِي فِي وَقْتِي", "O Allah, bless my time."],
  ["اللَّهُمَّ بَارِكْ لِي فِي رِزْقِي", "O Allah, bless my provision."],
  ["اللَّهُمَّ بَارِكْ لِي فِي أَهْلِي", "O Allah, bless my family."],
  ["اللَّهُمَّ اسْتَعْمِلْنِي فِي طَاعَتِكَ", "O Allah, use me in Your obedience."],
  ["اللَّهُمَّ اجْعَلْنِي مِفْتَاحًا لِلْخَيْرِ", "O Allah, make me a key to goodness."],
  ["اللَّهُمَّ لَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ", "O Allah, do not leave me to myself even for the blink of an eye."],
  ["اللَّهُمَّ اخْتِمْ لَنَا بِحُسْنِ الْخَاتِمَةِ", "O Allah, grant us a good ending."],
];

const titles = [
  "Acceptance from Allah", "Submission to Allah", "Good in This Life and the Next", "Patience and Victory", "Forgiveness for Mistakes", "A Steadfast Heart", "Mercy from Allah", "Forgiveness of Sins", "Returning After Wronging Ourselves", "Increase in Knowledge", "An Open Heart", "Ease in Your Affairs", "Forgiveness and Mercy", "In Need of Good", "Righteous Company", "Establishing Prayer", "Acceptance of Dua", "Forgiveness for Parents", "Mercy for Parents", "Family as Comfort", "Leadership in Taqwa", "Complete Our Light", "Forgive Us", "Reliance on Allah", "Returning to Allah", "The Final Return", "Protection from Trial", "Forgiveness for the Ummah", "A Clean Heart", "Gratitude for Blessings", "Good Deeds That Please Allah", "Mercy Among the Righteous", "Dua of Yunus", "Allah Is Sufficient", "The Best Protector", "Asking for Forgiveness", "Asking for Mercy", "Asking for Guidance", "Asking for Well-Being", "Asking for Provision", "Guidance, Taqwa, Purity, Contentment", "Beneficial Knowledge", "Pure Provision", "Accepted Deeds", "Protection from Anxiety", "Protection from Laziness", "Protection from Cowardice", "Protection from Debt", "Pardon and Forgiveness", "Istighfar", "Glorifying Allah", "Praise of Allah", "Magnifying Allah", "Tawheed", "Strength Through Allah", "Glory and Praise", "Glory of the Magnificent", "Salawat Upon the Prophet ﷺ", "Barakah Upon the Prophet ﷺ", "Leaving Home with Trust", "Good of the Day", "Protection from the Day's Harm", "Morning and Evening with Allah", "Life and Death Belong to Allah", "Sayyid al-Istighfar", "Servanthood to Allah", "Protection from Useless Knowledge", "A Humble Heart", "A Content Soul", "An Answered Dua", "A Good Ending in All Affairs", "Protection in Dunya and Akhirah", "Asking for Paradise", "Protection from the Fire", "Love of Allah", "Love of Allah's Beloved", "Love of Good Deeds", "Among Those Who Repent", "Among Those Who Purify", "Best of Life at the End", "Best of Deeds at the End", "Best Day Meeting Allah", "A Firm Heart", "O Turner of Hearts", "Correct My Religion", "Correct My Worldly Life", "Correct My Hereafter", "Beauty of Faith", "Guided and Guiding", "Seeking Allah's Pleasure", "Protection from Allah's Anger", "Asking for Well-Being", "Complete Healing", "Bless My Time", "Bless My Provision", "Bless My Family", "Use Me in Obedience", "Key to Goodness", "Do Not Leave Me to Myself", "A Good Final Ending",
];

function referenceFor(index: number) { return index < 35 ? "Qur'an" : "Daily du'a / Hisn al-Muslim style collection"; }
function frequencyFor(index: number) { if (index >= 60 && index <= 65) return "Morning and evening"; if (index === 57 || index === 58) return "Any time, especially when remembering the Prophet ﷺ"; if (index === 48) return "Often throughout the day"; return "Once daily or whenever needed"; }

export const extendedDuaBank: DuaItem[] = duas.map(([arabicText, translation], index) => ({
  id: `dua-${String(index + 1).padStart(3, "0")}`,
  title: titles[index] || "Daily Dua",
  arabicText,
  transliteration: "",
  translation,
  reference: referenceFor(index),
  note: frequencyFor(index),
  themes: ["Du'a", "Daily", index < 35 ? "Qur'an" : "Dhikr"],
}));
