export type SmallMission = { id: number; category: string; title: string; timeMin: number; timeMax: number };

const categories: Array<[string, string[]]> = [
  ["Home & Cleaning", ["Clean your room fully.", "Clean your car inside.", "Wash your car outside.", "Organize your closet.", "Fold and put away laundry.", "Deep clean your desk.", "Organize your backpack or work bag.", "Clean your bathroom sink and mirror.", "Scrub your shower or bathtub.", "Vacuum your room.", "Mop one area of the house.", "Take out all trash in the house.", "Clean the kitchen counters.", "Clean the microwave.", "Clean the fridge shelves.", "Throw away expired food.", "Organize the pantry.", "Organize your shoes.", "Clean under your bed.", "Dust your room.", "Wipe all door handles and light switches.", "Clean your windows.", "Organize your drawers.", "Make your bed nicely.", "Clean your nightstand.", "Organize your charging cables.", "Clean your phone case.", "Clean your laptop keyboard and screen.", "Wash your bedsheets.", "Rearrange your room to make it feel fresh."]],
  ["Family & Kindness", ["Buy a small gift for your dad.", "Buy a small gift for your mom.", "Write a thank-you note to a parent.", "Call your grandparents.", "Visit a family member.", "Make tea or coffee for someone.", "Help your mom with one chore.", "Help your dad with one task.", "Clean a sibling’s room as a surprise.", "Buy dessert for your family.", "Cook breakfast for your family.", "Cook dinner for your family.", "Wash dishes without being asked.", "Ask a family member how they are really doing.", "Spend one hour with your younger sibling.", "Teach your sibling something useful.", "Help a family member organize something.", "Make a family photo folder.", "Print one family photo and frame it.", "Send a kind message to a relative.", "Write a list of 10 things you appreciate about your family.", "Plan a family game night.", "Take your parent out for coffee.", "Help carry groceries.", "Clean the family living room.", "Make a small care package for someone.", "Apologize to someone you hurt.", "Forgive someone privately and make dua for them.", "Compliment 5 people sincerely.", "Give charity, even a small amount."]],
  ["Faith & Spiritual", ["Pray all prayers on time for one day.", "Read Qur’an for 30 minutes.", "Memorize one short surah.", "Memorize one dua.", "Review surahs you already know.", "Listen to a beneficial Islamic lecture.", "Write down 10 blessings from Allah.", "Make dua for 20 people by name.", "Read the meaning of one surah.", "Learn one name of Allah deeply.", "Make istighfar 500 times.", "Send salawat 500 times.", "Clean your prayer area.", "Prepare a small sadaqah jar.", "Visit the masjid outside of Jummah.", "Pray 2 rak‘ahs of gratitude.", "Read a short story of a Sahabi.", "Teach a younger person one Islamic lesson.", "Write your personal dua list.", "Make a plan to improve one bad habit for Allah.", "Watch a khutbah and take notes.", "Learn the meaning of what you say in salah.", "Make a morning athkar routine card.", "Make an evening athkar routine card.", "Call someone only to make them feel loved for Allah’s sake."]],
  ["Health & Fitness", ["Walk for 30 minutes.", "Walk 5,000 steps.", "Do a home workout.", "Stretch for 30 minutes.", "Do a full body mobility session.", "Prepare healthy meals for tomorrow.", "Make a healthy grocery list.", "Drink only water for the day.", "Clean your water bottle.", "Organize your supplements or medicine cabinet.", "Take a relaxing shower and reset.", "Sleep early for one night.", "Plan your sleep schedule for the week.", "Go outside for fresh air.", "Do 20 minutes of deep breathing.", "Try a beginner yoga or mobility video.", "Make a weight-loss or fitness progress chart.", "Go for a bike ride.", "Play a sport for one hour.", "Do a 30-minute boxing/cardio session.", "Prep a fruit bowl.", "Make a high-protein snack.", "Track your food honestly for one day.", "Clean your gym shoes.", "Pack your gym bag for tomorrow."]],
  ["Productivity & Organization", ["Plan your week.", "Plan your day tomorrow.", "Clean your email inbox.", "Delete useless photos from your phone.", "Organize your phone apps.", "Update your calendar.", "Make a to-do list for school/work.", "Finish one overdue task.", "Organize your Google Drive.", "Organize your desktop files.", "Create a budget for the month.", "Check your bank transactions.", "Cancel one subscription you do not need.", "Update your resume.", "Update your LinkedIn profile.", "Apply to one internship or job.", "Write a professional email you’ve been delaying.", "Make a list of 10 goals.", "Break one big goal into small steps.", "Create a morning routine.", "Create a night routine.", "Make a study schedule.", "Organize your notebooks.", "Review your grades or progress.", "Set reminders for important deadlines."]],
  ["Learning & Skill", ["Read 20 pages of a book.", "Watch a useful educational video and take notes.", "Learn 10 new words.", "Practice Arabic for 30 minutes.", "Practice public speaking for 20 minutes.", "Record yourself giving a short speech.", "Learn a new recipe.", "Learn one Excel skill.", "Learn one Canva design skill.", "Learn one AI tool skill.", "Watch a pharmacy-related video.", "Study one school topic for 45 minutes.", "Make flashcards for one topic.", "Teach someone something you learned.", "Write a one-page reflection.", "Practice typing faster.", "Learn how to fix one household item.", "Learn basic car maintenance.", "Watch a documentary.", "Summarize an article in your own words."]],
  ["Social & Relationship", ["Text an old friend.", "Call a friend instead of texting.", "Ask someone to meet for coffee.", "Send a motivational message to someone.", "Check on someone who has been quiet.", "Thank a teacher, mentor, or coach.", "Write a recommendation or review for someone’s business.", "Plan a hangout with friends.", "Make a birthday list so you remember people.", "Send a voice note to someone you appreciate.", "Help a friend with homework or work.", "Share a useful resource with someone.", "Invite someone to the masjid.", "Sit with someone who may feel left out.", "Make someone laugh in a halal way."]],
  ["Community & Service", ["Pick up trash in your neighborhood.", "Donate clothes you do not wear.", "Donate food to a pantry.", "Help at the masjid for one hour.", "Make a flyer for a community event.", "Message someone asking if they need help.", "Prepare hygiene kits for people in need.", "Volunteer for a local event.", "Help clean a community space.", "Bring water/snacks to volunteers.", "Make a list of community service ideas.", "Create a small fundraiser idea.", "Share a beneficial reminder online.", "Help someone carry something heavy.", "Leave a positive review for a local Muslim business."]],
  ["Personal Reset & Self-Improvement", ["Take a no-phone break for one hour.", "Journal about your life right now.", "Write a letter to your future self.", "Make a vision board.", "Clean your mind by writing all your worries down.", "Sit alone and reflect for 30 minutes.", "Make a list of habits you want to stop.", "Make a list of habits you want to build.", "Delete apps that waste your time.", "Set screen time limits.", "Organize your passwords.", "Create a life reset checklist.", "Make your room smell good and feel peaceful.", "Do one thing you have been avoiding.", "Spend 2 hours improving your life with no distractions."]],
];

export const smallMissionBank: SmallMission[] = categories.flatMap(([category, missions]) => missions.map((title, index) => ({
  id: categories.slice(0, categories.findIndex(([name]) => name === category)).reduce((sum, [, list]) => sum + list.length, 0) + index + 1,
  category,
  title,
  timeMin: 20,
  timeMax: 120,
})));

function dayOfYear(date: Date) {
  const start = new Date(date.getFullYear(), 0, 0);
  return Math.floor((date.getTime() - start.getTime()) / 86400000);
}

export function getDailySmallMissions(date = new Date(), count = 2) {
  const day = dayOfYear(date);
  return Array.from({ length: count }, (_, i) => smallMissionBank[(day * 7 + i * 53) % smallMissionBank.length]);
}
